### ISSUE TITLE
Use new Javascript GC apis to leak less memory

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1006]
@phorward has discussed here #693 the fact that we leak lots of memory. With `FinalizationRegistry` and `WeakRef` we can do better. We must still leak general Python ==> javascript ==> Python reference loops (I believe I can prove that it is theoretically impossible to detect these with the available APIs unless we are allowed to only use javascript objects produced by pyodide), but there are two cases that we can handle:
1. the case when no reference loops cross the javascript / python border, and
2. the case when the js objects involved in the reference loop are only referenced in ways that the Python GC knows about (so the javascript objects are owned by Python).

Case 1 is simple, case 2 is complicated (we'd have to implement a mark and sweep algorithm) and definitely not worth doing except for fun.
One issue that would come up with testing these things is that Javascript gives no way to ask for the garbage collector to run. So there's no way to get a deterministic expected behavior -- how do you test "Javascript will eventually do this"?

**Comment by mgreminger** [comment]
Yes, utilizing `FinalizationRegistry` would be good to automate reference count decrementing of Python created objects when they go out of scope on the JS side. Right now, there is the manual approach to do this using the [`.destroy()`](https://pyodide.readthedocs.io/en/latest/type_conversions.html?highlight=.destroy()#python-from-javascript) method from the JS side, which was necessitated before the availability of `FinalizationRegistry` . Of course, the manual `.destroy()` method doesn't solve the issue raised in #693, but using `FinalizationRegistry` should allow us to fix this. However, to make this work correctly, we'll need to get the reference counting correct for Python objects used on the javsacript side. If the same python is sent to javascript multiple times, its reference count in python needs to be increased each time. This is currently not handled correctly (I initially thought this was due to #708, but the same thing happens in pyodide v15, which was before #708). The following example has an error when the first reference to the Python object is destroyed while the second reference is still in scope. This will need to be fixed for `FinalizationRegistry` to work properly otherwise Python may garbage collect objects that are still in scope on the JS side like in the example below.


```html
<!DOCTYPE html>
<html>
  <head>
      <script type="text/javascript">
          // set the pyodide files URL (packages.json, pyodide.asm.data etc)
          window.languagePluginUrl = 'https://cdn.jsdelivr.net/pyodide/v0.16.1/full/';
      </script>
      <script src="https://cdn.jsdelivr.net/pyodide/v0.16.1/full/pyodide.js"></script>
  </head>
  <body>
    Pyodide test page <br>
    Open your browser console to see pyodide output
    <script type="text/javascript">
          languagePluginLoader.then(function () {
            ref1 = pyodide.runPython('a=10');
            ref2 = pyodide.runPython('a');

            console.log('first try:', ref2);

            // manually decrement the python reference count
            // this was the only option before FinalizationRegistry was available
            // ref2 should still be enough to keep the python object around
            ref1.destroy();

            // force python garbage collection
            pyodide.runPython(`
import gc
gc.collect()
            `);

            console.log('second try:', ref2); // results in error: TypeError: ref1 is undefined
          });
    </script>
  </body>
</html>
```

**Comment by hoodmane** [comment]
@mgreminger Thanks for pointing out that bug. I think that we should probably do actual refcounting rather than the current approach which is a bit naive. On a related note, I also want to add `WeakPyProxy` and `WeakJsProxy` APIs.

**Comment by hoodmane** [comment]
I don't understand this code though:
```javascript
ref1 = pyodide.runPython('a=10');
ref2 = pyodide.runPython('a');
...
ref1.destroy();
```
The first call returns `None` and py2js converts `None` ==> `undefined` so `ref1` should be `undefined`. The second call returns `10` (an `int`) and `py2js` converts `int` ==> `number` so `ref2` should javascript `10`. Then `ref1.destroy();` will throw a reference error.

It's clear though how to make a correct example that probably does what you claim.

**Comment by mgreminger** [comment]
Thanks @hoodmane for the correction. Yes, you're absolutely correct, I was trying to destroy undefined which was causing the error. All of this only applies to custom Python objects anyway so I shouldn't have use an integer as an example either. The following code actually correctly illustrates the issue using a function as the python object:

```html
<!DOCTYPE html>
<html>
  <head>
      <script type="text/javascript">
          // set the pyodide files URL (packages.json, pyodide.asm.data etc)
          window.languagePluginUrl = 'https://cdn.jsdelivr.net/pyodide/v0.16.1/full/';
      </script>
      <script src="https://cdn.jsdelivr.net/pyodide/v0.16.1/full/pyodide.js"></script>
  </head>
  <body>
    Pyodide test page <br>
    Open your browser console to see pyodide output
    <script type="text/javascript">
          languagePluginLoader.then(function () {
            ref1 = pyodide.runPython('a=lambda x: 2*x; a');
            ref2 = pyodide.runPython('a');

            console.log('first try:', ref2(10));

            // manually decrement the python reference count
            // this was the only option before FinalizationRegistry was available
            // ref2 should still be enough to keep the python object around
            ref1.destroy();

            // force python garbage collection
            pyodide.runPython(`
import gc
gc.collect()
            `);

            console.log('second try:', ref2(20)); // results in error: Object has already been destroyed
          });
    </script>
  </body>
</html>
```
