### ISSUE TITLE
Not all tests pass in master branch

### ISSUE THREAD

**Issue by albertas** [pyodide/pyodide#1258]
I have executed all master df3861e branch  tests in the pre-built docker container and got 5 tests failing:
- FAILED src/tests/test_asyncio.py::test_await_pyproxy_eval_async[firefox]
- FAILED src/tests/test_asyncio.py::test_await_pyproxy_async_def[firefox] 
- FAILED src/tests/test_asyncio.py::test_await_pyproxy_eval_async[chrome] 
- FAILED src/tests/test_asyncio.py::test_await_pyproxy_async_def[chrome]
- FAILED src/tests/test_core_python.py::test_cpython_core[test_compile-chrome]

The first four failed with `NotImplementedError` and the last one failed with:

```
Traceback (most recent call last):
  File "/lib/python3.8/test/libregrtest/main.py", line 634, in main
    self._main(tests, kwargs)
  File "/lib/python3.8/test/libregrtest/main.py", line 704, in _main
    sys.exit(2)
SystemExit: 2
```

I suggest marking these 5 tests to be skipped to make all master tests pass. I managed to do so by:
1. Adding `@pytest.mark.skip` decorator for [test_await_pyproxy_async_def](https://github.com/iodide-project/pyodide/blob/master/src/tests/test_asyncio.py#L339) and [test_await_pyproxy_eval_async](https://github.com/iodide-project/pyodide/blob/master/src/tests/test_asyncio.py#L266).
2. Commenting out [this line]( https://github.com/iodide-project/pyodide/blob/master/src/tests/python_tests.txt#L129). This also removed one passing test.

**Comment by rth** [comment]
> the pre-built docker container

Please try the regular (non-prebuilt) pyodide Docker container, after running `make clean-all` then `git clean -xdf` (to remove all untracked files in git).  There have been a lot of changes in the code base since the release, and the pre-built container would have build artifacts from a month ago. I'm not sure what happens if you mix those with the latest version of code from master -- probably nothing good. The prebuilt image is meant to be run with the last release not master.

**Comment by albertas** [comment]
I have tried:

```
make clean-all
git clean -xdf
./run_docker
make
pytest src/ pyodide_build/ packages/*/test_*
```
And the same 5 tests still failed.

**Comment by rth** [comment]
You are right and I can reproduce locally. `test_await_pyproxy_eval_async` and `test_await_pyproxy_eval_async` also actually fail in CI on master however because we use `tools/pytest_wrapper.py` to re-run failed tests, they pass the second time they are run.

This was already the case in https://github.com/iodide-project/pyodide/pull/1170. @hoodmane Could you have a look? Something is not quite stable in those tests or some earlier tests modify the global state when they shouldn't.

> FAILED src/tests/test_core_python.py::test_cpython_core[test_compile-chrome]

Yes, I have seen that one failing in the past occasionally. You can probably ignore it, or skip it on Chrome indeed. As long as it doesn't fail in the CI we probably don't need to worry about it too much.

**Comment by hoodmane** [comment]
Thanks for the report @albertas. 

> earlier tests modify the global state when they shouldn't

Yes.

Yes.

**Comment by hoodmane** [comment]
Closed because it's out of date (though it's still true that not all tests pass on main).
