### ISSUE TITLE
How to call an async JavaScript function from python?

### ISSUE THREAD

**Issue by daoxian** [pyodide/pyodide#1309]
the callee JS function is:

```
import { Tensor, InferenceSession } from "onnxjs";
class SiamRPNTracker {
  async inference() {
      //...
      await this.session_first.run([x], ['xf']);
  }
}
```

I want to call this inference() method in python by 
```
import asyncio
asyncio.run(js.g_tracker.inference(x_crop, x_crop.shape, 1, True)) 

```

But it throws an exception:

> ValueError: a coroutine was expected, got [object Promise]

So how can I fulfil the call?

**Comment by hoodmane** [comment]
A coroutine in Python won't run by default, it has to be scheduled. (If you never schedule the coroutine, its destructor will print a `RuntimeWarning`. `asyncio.run` schedules a coroutine. On the other hand, a `Future` represents a result that has already been scheduled. A Javascript promise is like a `Future` since the corresponding computation has already been scheduled. Anyways, if you call a Javascript asynchronous function, no call to anything like `asyncio.run` is necessary, it will eventually happen. However, the asynchronous javascript function runs on the same thread as pyodide, so if you don't ever yield the thread it won't ever execute.

You can `await` the promise or use `asyncio.gather`, or just let the current pyodide code finish before executing. You can also use explicit yields like `await sleep(0);` to make sure the other task is given time and makes progress even while the current task keeps going.

**Comment by daoxian** [comment]
> A coroutine in Python won't run by default, it has to be scheduled. (If you never schedule the coroutine, its destructor will print a `RuntimeWarning`). `asyncio.run` schedules a coroutine.

asyncio.run throws an error when calling a Python async function from JS:
![image](https://user-images.githubusercontent.com/34263430/110431724-23208080-80e9-11eb-88f3-f513b67a41f2.png)

**Comment by daoxian** [comment]
@hoodmane  I found #1170  is suitable for solving above problem.  So how to use  this feature?

**Comment by hoodmane** [comment]
As far as I can tell awaiting a python async function works fine.
```js
let test = pyodide.runPython(`
   async def test():
      return 2
   test
`);
await test();
```
returns `2` as expected.

**Comment by hoodmane** [comment]
@dmondev Yes this should work using the development version of pyodide (but not in version 0.16.1). There should be complete interoperability between Python and Javascript awaitables now. Any javascript object with a `then` method is considered awaitable. It can be imported into Python and `await`ed from Python. You can also call `then` or `catch` from Python. The `finally` method is inconvenient to access currently because `finally` is a Python reserved keyword.
You can also turn the Promise into a future with `asyncio.ensure_future` and then pass it to any Python API expecting a future. Any Python `awaitable` can be imported into `Javascript` and can be `await`ed from Javascript with the expected result.

For instance I just tested the following code here: https://pyodide-cdn2.iodide.io/dev/full/console.html
```js
await pyodide.runPythonAsync(`
    from js import fetch, console;
    o = await (await fetch("packages.json")).json()
    o.dependencies.astropy[0]
`);
```
or
```js
async function fetch_json(url){
    let resp = await fetch(url);
    return await resp.json();
}
globalThis.fetch_json = fetch_json;
await pyodide.runPythonAsync(`
    from js import fetch_json;
    o = await fetch_json("packages.json")
    o.dependencies.astropy[0]
`);
```

![image](https://user-images.githubusercontent.com/8739626/110548806-fd45ac80-80e5-11eb-89f8-89e609a0d76a.png)

**Comment by dmondev** [comment]
@hoodmane Thank you very much !! Really appreciate your prompt responses.

I was able to kinda do it using a lambda, but not exactly how I would like it. I'm going to switch to dev version and give it a try.

```python
import js

def do_it(data):
  print(data)

js.getSome().then(lambda d: do_it(d))

```

**Comment by daoxian** [comment]
> As far as I can tell awaiting a python async function works fine.
> 
> ```js
> let test = pyodide.runPython(`
>    async def test():
>       return 2
>    test
> `);
> await test();
> ```
> 
> returns `2` as expected.

![image](https://user-images.githubusercontent.com/34263430/110566843-8e229380-818b-11eb-8e5f-f42a4f97f998.png)

Maybe relating to old pyodide version?

**Comment by dmondev** [comment]
How can I iterate to the JsProxy attributes in Python ?

I changed the code above, (in the development version) to use "for in", but I get an error stating that the JsProxy is not Iterable. 

![image](https://user-images.githubusercontent.com/14889087/111069614-427e2b80-84a4-11eb-803d-00a4007506c4.png)

And the syntax above, that works in 0.16.1, also doesn't work in the development version:

![image](https://user-images.githubusercontent.com/14889087/111070472-4f9d1980-84a8-11eb-886c-22b63c604ce1.png)

**Comment by hoodmane** [comment]
Currently one way to do this is:
```py
from js import fetch
resp = await fetch("packages.json")
json = await resp.json()
d = []
for [i, _] in json.dependencies.object_entries():
   d.append(i)
```
We should probably add methods `object_keys()` and `object_values()` too.
In the current dev branch we only allow iteration over things that are iterable in Javascript, in the sense that they have a `Symbol.iterator` method. For instance, the following would also fail in javascript:
```js
for(let i of json){ // ==> TypeError: json is not iterable
  d.push(i);
}
```

**Comment by hoodmane** [comment]
@rth This is going to be an important migration note for v0.17.

**Comment by hoodmane** [comment]
Okay I'm closing this as answered, the `to_js` problem is still present but it has a dedicated thread in #1529.
