### ISSUE TITLE
Handling unsupported CPython stdlib modules

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#144]
Currently modules from the CPython standard library that are not supported, such as,
 - ctypes
 - threading ?
 - etc.. see more complete list in [remove_modules.txt ](https://github.com/iodide-project/pyodide/blob/4331456f7d4d6b8c47437f616ed92a835eaafaeb/remove_modules.txt)

cannot be imported in CPython wasm environment, meaning that every time one of those is imported in a Python package, [it needs to be patched](https://github.com/iodide-project/pyodide/search?q=threading&unscoped_q=threading), which is time consuming. 

The question is, could it be beneficial to add some mechanism to allow imports of these modules (and of the functions/classes they contain), then error when any of these functions classes are actually used? The difference is that in a user package, the failure would happen for the unsupported functionality instead of for the whole package at import time (short of patching it).

**Comment by madhur-tandon** [comment]
Can I work on this? I think this one would be good to learn some internals of C extensions too. Could you assign me @mdboom @rth ?

**Comment by mdboom** [comment]
Sure.  You shouldn't have to actually change any of the extensions.  The idea here is to basically:

1) Identify which modules in the stdlib don't import (due to limitations of the WebAssembly environment)
2) Modify our import hook (in `jsimport.c`) which currently handles the `from js import X` functionality, to create dummy modules when one of these "broken" modules is imported.
3) When using anything in the dummy module, throw an `ImportError` at that time, rather than when the module was first imported.

This will allow us to use libraries that import these modules but only use them to implement optional features that the user may not need to use.

**Comment by rth** [comment]
In particular, I think we could try to re-export `dummy_threading` and `multiprocessing.dummy` as `threading` and `multiprocessing` for now. That would reduce the amounts of patches needed in packages.

**Comment by rth** [comment]
> Modify our import hook (in jsimport.c) which currently handles the from js import X functionality, to create dummy modules when one of these "broken" modules is imported.

Actually it's might be easier, to set `set.modules` in `sitecustomize.py` which is run at startup,
```
import dummy_threading  # noqa                                                            
sys.modules['threading'] = dummy_threading
```
In the case of `threading` I'm not longer sure it's a good idea, as when doing this, some  stdlib tests start to fail, as either they rely on private threading attributes (not available in `dummy_threading`) or they lead to deadlock when a dummy thread is started but because it's not run in background thread synchronization doesn't work as expected. So maybe we don't even need to patch threading, `import threading` generally works, but creation of threads themselves fail.

**Comment by rth** [comment]
Closing as the current situation is mostly OK. We can open specific per-module issues if needed.
