### ISSUE TITLE
Remove loadPackagesFromImports from runPythonAsync?

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1496]
This would be a backwards incompatible API change but I think it's for the best.

**Comment by phorward** [comment]
> This would be a backwards incompatible API change but I think it's for the best.

Can you shortly explain a reason for this change please?

**Comment by rth** [comment]
I think the initial reason for this function was to be able load imported packages when used in Pyodide.

Now that we have async support I agree that it might be good to have a function to run Python code asynchronously that doesn't try to make network calls and load some packages at the same time.

This means that current REPL/Notebook environments would have to call `loadPackagesFromImports` explicitly, but IMO it's likely preferable anyway to be able to show the user some UI that the package are loading/done loading instead of relying on the console log.

**Comment by rth** [comment]
And I guess we would rather not tell users to use `Module.pyodide_py.eval_code_async` directly as not asking them to [delete the resulting PyProxy object at the end](https://github.com/pyodide/pyodide/blob/dba1093b09d8de94fca059b8b4abbbde47166160/src/pyodide.js#L696)  is more user friendly.
