### ISSUE TITLE
os.name returns `posix`

### ISSUE THREAD

**Issue by karthiknadig** [pyodide/pyodide#1610]
I think this should return something other than `posix` or `nt`.

/cc @int19h

**Comment by rth** [comment]
True, but it's more an issue for CPython. We are just following the docs which says,
```
The following names have currently been registered: 'posix', 'nt', 'java'.

See also

sys.platform has a finer granularity. os.uname() gives system-dependent version information.

The platform module provides detailed checks for the system’s identity.
```
and in the case of Pyodide `sys.platform` returns `"emscripten"`.

**Comment by rth** [comment]
Actually, this is likely the expected behavior. Emscipten does aim to emulate the POSIX API even if the emulation is not perfect.

In any case, we should leave this decision to the CPython team, and currently in the CPython 3.11a7 WASM build https://cheimes.fedorapeople.org/python-wasm/ the behavior is the same.  See related discussion in https://discuss.python.org/t/expected-behavior-for-unsupported-stdlib-modules-in-the-browser/15689/8

So I'm going to close this issue. Thanks for the report.
