### ISSUE TITLE
Strange behavior with importing seaborn ! 

### ISSUE THREAD

**Issue by unhott** [pyodide/pyodide#1619]
Hello! 
Someone ran into issues importing seaborn through a starboard notebook and, at first it seemed like a simple issue of wheel availability and versions. 
But in trying to find a specific version that maybe works, something just doesn't seem right. 

Ultimately I think that 
micropip.install('seaborn==0.9.0') worked in pyodide 0.16 but it doesn't seem to work in 0.17, and I can't quite figure out why! 

The post + my original response is here, for further context: 
https://community.starboard.gg/t/issue-with-micropip-installing-packages/100

**Comment by hoodmane** [comment]
So I guess the wheel format consists of two zip files archives next to each other, first a small "header zip" and then a larger body zip. In the seaborn case, the headers are 8kb and the body is 950kb. pip makes a series of HTTP range requests for the wheel until it finds a prefix which is a valid zip file, this is the "header zip". Then pip can unzip this and find out what the dependencies are, without needed to download the entire wheel.

Unfortunately, we can't use range requests with `pythonhosted.org` because range requests are preflighted and require CORS, but `pythonhosted.org` does not respond with the `ACCEPT-ORIGIN` header. So this means we need to download the entire wheel up front.

This seems like a dumb design though: why isn't this information part of the json file that pypi serves? This "do range requests until we find the complete header zip" approach seems unnecessarily complicated...

**Comment by hoodmane** [comment]
Okay so apparently CORS is missing specifically from range requests. I opened an issue about this: https://github.com/pypa/conveyor/issues/11

**Comment by unhott** [comment]
Thanks for figuring out the cause!

**Comment by hoodmane** [comment]
Okay this will be fixed in v0.18.0. Thanks again for this very useful bug report.

**Comment by unhott** [comment]
I'm stoked! Thanks :D
