### ISSUE TITLE
Investigating pillow JPEG error

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#1817]
Related Issues:
- #1781
- #1632
- #1198
- #1201
- #1657 (might be related)

I have been investigating an error in pillow JPEG encode/decode functionality,
and I found that something wrong is happening because libjpeg library is linked to pillow side module.

When I [modified the code](https://github.com/ryanking13/pyodide/commit/4eead177abc8b7fb6f1295e74e81fb3f1ef3243f) such as:

1. **Link libjpeg with main module**

![image](https://user-images.githubusercontent.com/24893111/132082200-0b313d73-4c9d-472d-9a14-3c1954e487bb.png)

2. **Remove linking ligjpeg in pillow side module**

![image](https://user-images.githubusercontent.com/24893111/132082187-806b4c90-f51f-4739-af8e-85e526099656.png)

It looks like the jpeg error is fixed.

---

Now, things I want to discuss are:

1. **Why linking a library to a side module generates an error?**

The [Emscripten docs](https://github.com/emscripten-core/emscripten/wiki/Linking) says:

```
1. Main modules, which have system libraries linked in.
2. Side modules, which do not have system libraries linked in.
```

As it says, Emscripten suggests not to link system libraries to a side module.

But [when I made a simple Emscripten code which links system libraries to a side module](https://gist.github.com/ryanking13/5e0e0d36a60ed947b94286e82b4a40d7), It builds and runs with no error.
I am very new to Emscripten, so I am not sure how linking system libraries to a side module can generates an error.

2. Is adding ligjpeg to the main module is the right solution?

Adding libjpeg to the main module results in the code size increase of pyodide.asm.{js,wasm}.

- pyodide.asm.js: ~32KB increased
- pyodide.asm.wasm: ~440KB increased

```sh
# code size in bytes (linking libjpeg to the pillow)
1723564 pillow.data
38899 pillow.js
1998551 pyodide.asm.js
11729609 pyodide.asm.wasm
```
```
#  code size in bytes (linking libjpeg to the main module)
782498 pillow.data
23395 pillow.js
2031046 pyodide.asm.js
12180594 pyodide.asm.wasm
```

I'm not sure this amount of code size increase is critical.
But if there is another solution not linking libjpeg to the main module, I believe that will be better.
(Maybe we can select whether to link libjpeg dynamically when building?)

**Comment by rth** [comment]
Thanks for investigating this @ryanking13 !

> Why linking a library to a side module generates an error?

It's been a while since I looked into those emscripten aspects, so it might be easier to ask emscripten devs (or read the emscripten docs/code implementation).

> The Emscripten docs says:

Note that it's a wiki page that is not part of the Github repo. It was last updated after the 2.0 release, but I'm not sure it is systematically updated with changes in the repo. So it might be more reliable to instead read discussion in issues/code comments.

> Is adding ligjpeg to the main module is the right solution?
> I'm not sure this amount of code size increase is critical.
> (Maybe we can select whether to link libjpeg dynamically when building?)

The .wasm, .js code has quite good compression so in would probably translate to 150kB (compressed) extra to download. It's not ideal, but also having JPEG working is worth it IMO. So in a first approach, we can certainly merge your fix as is.

In the long term though, yes this is not ideal. In https://github.com/pyodide/pyodide/issues/646 I was hoping we could remove freetype, libpng from the main module and statically link them in the side module as required, however last I tried, I haven't managed to make it work. Maybe a better solution would be to make standalone packages for libjpeg, libpng, libfreetype, load them as dependencies when necessary and then dynamically link them as needed. That's what we are currently doing for CLAPACK for instance. cc @joemarshall who might have other ideas.

Also see for instance how lxml / libxml is built without linking libxml into the main module.

**Comment by hoodmane** [comment]
Related: https://github.com/emscripten-core/emscripten/issues/14488

**Comment by ryanking13** [comment]
> Also see for instance how lxml / libxml is built without linking libxml into the main module.

I found that there is a standalone libxml package and lxml links it.
So in the long term, building standalone libjpeg package will be a better solution, thanks @rth!
