### ISSUE TITLE
Rate Limiting in Docker Hub: Alternative Container Registries for pyodide/pyodide

### ISSUE THREAD

**Issue by ehfd** [pyodide/pyodide#1851]
The [rate limiting](https://www.docker.com/increase-rate-limits) issues for Docker Hub is recently getting notorious, especially in multi-user environments. This clearly affects IPs which downloads more than 100 containers (any container in Docker Hub) over 240 minutes. The most severely affected are bare metal Kubernetes clusters and self-hosted CI runners.
GitHub Packages Container Repository (ghcr.io) and quay.io are the most representative alternatives which host unlimited free containers for public code repositories. Out of the two, ghcr.io will be easiest to work with.
It can be paired with free CIs that are also free for public code repositories without limitations in build minutes, which includes GitHub Actions & [Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted), GitLab/GitGud Pipelines, Buildkite, Cirrus CI, Semaphore, Travis CI, and others. Peakflow.io free for private repositories. [Reference](https://github.com/ligurio/awesome-ci)
Out of these, GitHub Actions or Azure Pipelines would be easiest to use.

Will it be possible to add the containers to GitHub Packages Container Registry (ghcr.io) in addition to Docker Hub?

**Comment by rth** [comment]
Thanks for raising this issue @ehfd ! Yes, we could also upload images to ghcr.io.

We actually already have the CI setup for the [pre-build Docker image](https://github.com/pyodide/pyodide/blob/main/.github/workflows/prebuilt_docker_image.yaml), though we are currently not using it. We would need to update that to trigger on tags and upload to ghcr.io additionally.

As for the non-prebuilt image, we might need a similar setup but still with a manual GH Actions trigger, since those are not updated at the same time as releases.

PRs for both setups would be welcome.
