### ISSUE TITLE
micropip should report all dependent packages without wheels in one go

### ISSUE THREAD

**Issue by yuvipanda** [pyodide/pyodide#1966]
## 🚀 Feature

When installing packages via `micropip`, if there are dependents that don't have pure python wheels, it errors out on the first such dependent. However, it would be much nicer if it could instead collect *all* the dependents that don't have wheels, and print them out in one go before exiting

### Motivation

I was trying to get the [nbconvert](https://github.com/jupyter/nbconvert/) package installed on pyiodide. It failed with pyristant not having pure python wheels. So I [made some](https://github.com/yuvipanda/pyiodide-nbconvert/releases/tag/pyrsistent-0.18.0) and was excited to try it again. But this time it now errors with [pyzmq](https://github.com/zeromq/pyzmq) not having any wheels. And now I'm not sure which other packages will error out!

### Pitch

When I run `micropip.install('nbconvert')`, I want it to tell me exactly which dependent packages are causing installation to fail.

P.S. AMAZING PROJECT, MUCH <3 TO EVERYONE INVOLVED

**Comment by rth** [comment]
Thanks for the feedback! I agree that this would be much more user friendly.

We could have a look at how to implement it. One thing to keep in mind is that until PyPi has reliable JSON API for dependencies, we have to parse the dependencies from the wheel. So if there is no pure Python wheel for a package, we can't get its dependencies.

Otherwise this change would likely mean to keep going with the installation even if a wheel is missing, then report all the errors at the end.

**Comment by ryanking13** [comment]
> Otherwise this change would likely mean to keep going with the installation even if a wheel is missing, then report all the errors at the end.

If we want to keep the behavior of `micropip.install` failing fast, we may design a new API such as `micropip.installable` which checks missing wheels, not sure which one is better.

**Comment by rth** [comment]
> we may design a new API such as micropip.installable

I think it might be better to keep the API surface to a minimum for future maintenance (and to avoid confusion). However indeed I'm not sure what would be best behavior on missing wheel between,
 - keep going and install the rest
 - keep going and download the rest of the dependencies (to get their respective dependencies) but don't install them on disk.
 
before finally reporting all the errors. Also it could be an option, between keep going or fail on first error.

**Comment by yuvipanda** [comment]
> keep going and download the rest of the dependencies (to get their respective dependencies) but don't install them on in the file system.

As a user, I like this option! It might mean you're downloading things that you then can't install, but that seems ok.

**Comment by bollwyvl** [comment]
I actually feel like the current fail-fast is a sensible default, with a (non-tracebackful) message saying how to change the invocation `keep_going=True` (or `fail_fast=False`). One or two, sure, maybe you can get around it, but a heavy ML library or something is going to pop 100 tightly-pinned, incompatible packages after downloading 200mb. 

With effective metadata, `dry_run=True` would be most magical of all, but again, if we're already paying to get the wheel into the emscripten VM, there's nothing for it.

@yuvipanda we'd of course _love_ patches sufficient to get up to `nbconvert` over on jupyterlite! Right now, we have a junk shim for `nbformat` and stop there, but further down there will be issues with `jsonschema` (because `pyrsistent`). 

looking further: `pandoc` and some LaTeX build chains have been demonstrated in emscripten... but i feel like we're going to have to wait for mamba-in-the-browser (which _would_ support `--dry-run` after downloading ~5 `repodata.json` files) before we'd be able to neatly install those with the correct versions, much less keep everything working, long term...

**Comment by ryanking13** [comment]
@yuvipanda You can now use `keep_going` parameter in micropip.install() to get the list of missing wheels. (#1967)

**Comment by yuvipanda** [comment]
Awesome, thank you @rth!

**Comment by rth** [comment]
@ryanking13 Did all the work :)
