### ISSUE TITLE
[feature request] To create wheel file for wasm-unknown-pyodide platform

### ISSUE THREAD

**Issue by hzhangxyz** [pyodide/pyodide#1971]
## 🚀 Feature

I hope we can compile a c ext module and package into a wheel file, so it can be used by others without recompiling

### Motivation

This is what we do in other platform like Linux and windows. Maybe one day, we can upload wasm wheel file directly to pypi.

**Comment by hoodmane** [comment]
I really like this idea too. It's been raised several times, though it could maybe use a new thread. @rth can probably link the old discussions about this.

**Comment by hoodmane** [comment]
Well I looked into this a bit. I successfully built a wheel, downloaded and unpacked it, and imported it. So this is completely feasible.

**Comment by rth** [comment]
Yes, there was also https://github.com/pyodide/pyodide/issues/655.

Can you share what you did exactly @hoodmane ?

The question is how to define binary compatibility. I suppose we could add an option to `pyodide-build` to output wheels instead of .js/.data, particularly for user packages. But then it's less straightforward to do dependency resolution.

Maybe we should keep one issue about this, not two..
