### ISSUE TITLE
Support platform specific dependencies in micropip

### ISSUE THREAD

**Issue by oeway** [pyodide/pyodide#1984]
I am trying to make a pip package which depends on different libraries based on whether it's pyodide or native python. However, I cannot find a way to find it out.
I have tried the following two methods in `setup.py`, without success:

```python
if platform.system() != "Emscripten":
    install_requires.extend([...])
```

```python
try:
    import pyodide
except ImportError:
    install_requires.extend([...])
```
One thing I don't understand is that all this two works in JupyterLite and the console, but somehow micropip.install is different.
Could you please provide some hint?

**Comment by rth** [comment]
If you were building a Pyodide package, one way is to check for the `PYODIDE` env variable, see https://pyodide.org/en/stable/usage/faq.html#how-to-detect-that-code-is-run-with-pyodide. `platform.system()` wouldn't work because setup.py is not actually run in WASM VM there, but rather by the host Python targeting WASM. The current approach is somewhat related to cross-compilation, but not strictly it either (https://github.com/pyodide/pyodide/issues/819)

In your case the issue is different. Note that we are currently unable to install pure  Python packages from sources, only wheels (since setuptools require multiprocessing). So the question is: can one dynamically change dependencies in a wheel in Python in general. I don't think so. Those are pretty much written in a static config file once you build the wheel, and have the config you used to build the wheel.

However there is a way to indicate [platform specific dependencies in requirements](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies). Also see [PEP 508](https://www.python.org/dev/peps/pep-0508/). So something like,
```
setup(
    ...,
    install_requires=[
        "requests >= 1.0;platform_system=='Emscripten'",
        "pyodide-requests >= 1.0;platform_system!='Emscripten'",
    ],
)
```
might  work once we add support for it in micropip. A PR would be very welcome and we should document this.

**Comment by rth** [comment]
Because we are already relying on [`packaging` for parsing requirements](https://github.com/pypa/packaging), it does most of the work,
```py
>>> from packaging.requirements import Requirement
>>> req = Requirement("pyodide-requests >= 1.0;platform_system=='Emscripten'")
>>> req
<Requirement('pyodide-requests>=1.0; platform_system == "Emscripten"')>
>>> req.name
'pyodide-requests'
>>> req.marker.evaluate()
True
```
and it looks like this is already implemented in micropip [here](https://github.com/pyodide/pyodide/blob/25d7bb5b9941de4be70fffc5703ee4194e59ccb2/packages/micropip/src/micropip/micropip.py#L224). We still need to improve documentation though.

**Comment by oeway** [comment]
@rth Thanks for the explanation! I confirm your solution works!

```python
>>> import micropip
>>> await micropip.install("pyotritonclient")
``` 

I will close this issue since you created other ones for the docs.
