### ISSUE TITLE
Improve log output of loaded packages in Browser

### ISSUE THREAD

**Issue by redfave** [pyodide/pyodide#1997]
## 🚀 Feature

Include **every** loaded package from pyodide/packages.json in console output of the Browser.
Also include which package is missing when it's requested and fails to load.

### Motivation

I started with a full package of pyodide 18.1 and would like to strip down all the unused packages to decrease the bundle size.
Therefore, I need to know which packages my scripts are using, so I can safely remove all the other packages. Luckily, the browser console spits out all the loaded packages when the loading of packages is finished:

`Loaded matplotlib, distutils, cycler, six, kiwisolver, numpy, pillow, pyparsing, python-dateutil, pytz`

The issue: This list is not complete. There are some packages (I guess only pyodide internal and not from PIP) which are loaded but aren't shown in the final log output, so I need to manually review all the logs. E.g.: 
`Loading micropip from http://localhost:8080/assets/pyodide/micropip.js`
...
`Loading packaging from http://localhost:8080/assets/pyodide/packaging.js`

The fact that I need micropip is to me obvious because I used it to install a wheel package. But the packaging package - ba dum tss - was not obvious at all to me. The error message when the packaging package is missing is not helpful at all:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'depends')
    at addPackage (load-pyodide.js:118)
    at addPackage (load-pyodide.js:119)
    at recursiveDependencies (load-pyodide.js:138)
    at _loadPackage (load-pyodide.js:158)
    at Object.loadPackage (load-pyodide.js:395)
    at async pyodide.ts:20`

**Comment by rth** [comment]
> Include every loaded package from pyodide/packages.json in console output of the Browser.

You can see this information in the dev tools, network tab. If you filter for ".data" files. This will generally be more reliable than logging. 

The logs are partial because it's produced by micropip, while a different mechanism (`pyodide.loadPackage`) is used to load micropip and Pyodide built packages #1470. Given that  `loadPackage` is also used internally by micropip, it would be not that onbvious to standardize those logs I'm not sure it's worth it since you have all this information better presented in the network tab of dev tools, in any case.

**Comment by ryanking13** [comment]
I think micropip.list (#1967) would be a solution for this? Though it's not implemented yet.

**Comment by ryanking13** [comment]
@redfave The lastest version of Pyodide now have `micropip.list()` (#1967) which lists all installed(loaded) packages.
If you don't want to run micropip, you can also look at `pyodide.loadedPackages`.
