### ISSUE TITLE
Move away from setup.py

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2189]
As mentioned by @henryiii is 

> Building via setup.py is very [heavily deprecated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html). I wouldn't recommend adding anything that depends on it.

With the other alternatives mentioned being [build](https://pypi.org/project/build/) and [installer](https://pypi.org/project/installer/).

I think build isolation would be a bit difficult to use in our case, as for instance when building scipy we need the patched numpy on the host and not the numpy version specified in pyproject.toml (which would be unpatched).  However trying to switch to `build`, for instance, without build isolation would certainly be worthwhile.

**Comment by henryiii** [comment]
flit now supports bootstrapping (as of 3.7, yesterday), and there's now a clear path for creating a working install/build system from scratch. See https://github.com/pypa/build/issues/394.

One alternative to disabling build isolation is to point at the local wheelhouse. Also, it seems to me that there should be a) a rule that all packages must match the PyPI name (something conda didn't do, largely because conda packages may not be Python packages), and b) a list of pure Python packages that simply get downloaded as wheels, rather than "being built" like a binary package with a formula.
