### ISSUE TITLE
Unable to retry loading pyodide, get error "Pyodide is already loading"

### ISSUE THREAD

**Issue by alexmojaki** [pyodide/pyodide#2255]
## 🐛 Bug

If `loadPyodide` fails, I'd like to call it again in case it's a transient network error. But trying this throws an error `Pyodide is already loading.`

### To Reproduce

I'm roughly doing this:

```js
import pRetry from 'p-retry';

pRetry(() => loadPyodide({indexURL: 'https://cdn.jsdelivr.net/pyodide/v0.19.0/full/'}), {retries: 3})
```

When I kill the network in the middle of loading, I get:

```
pyodide.js:243 Uncaught (in promise) Error: Pyodide is already loading.
    at loadPyodide (pyodide.js:243:1)
    at loadPyodideOnly (Worker.js:25:1)
    at RetryOperation._fn (index.js:50:1)
    at retry_operation.js:85:1
```

### Expected behavior

When `loadPyodide` fails, clean up and delete anything created during loading such as `globalThis.__pyodide_module`. This seems important for other reasons like memory usage. Hopefully it should allow `loadPyodide` to be called again. Or is there some deeper emscripten state problem with trying to load pyodide twice?

Adding some internal retrying logic to the various network requests would also be great, since I'm sure retrying all errors on my side isn't ideal. But I can understand if that raises tricky questions.

**Comment by hoodmane** [comment]
> Adding some internal retrying logic to the various network requests would also be great

I would be happy to accept work on this, but I will not do it myself.

> is there some deeper emscripten state problem with trying to load pyodide twice?

I am not 100% sure but I believe that there is not. My goal has been to remove all the global variables which has been taking a while. On the main branch, we have removed the need of `__pyodide_module` with #2027. So we're getting close.

The remaining issues with global variables are caused by us, not by Emscripten. In particular, the top level variables here are problematic:

https://github.com/pyodide/pyodide/blob/36d0e15300875d834a6b37b6199934f2d194e858/src/js/module.ts#L6

I'm not entirely sure how to fix this without messing up the documentation generation.

**Comment by hoodmane** [comment]
What I really want is for the bundler to fix the problem for me by bundling everything into a function that execs all the top level code and then exposing that function:
```js
function exec_module(config) {
  let module_exports;
  function init_module() {
    if (module_exports) {
      return;
    }
    module_exports = {};
    // top level contents of module.ts
    let Module = {};
    module_exports.Module = Module;
  }
  let load_pyodide_exports;
  function init_load_pyodide() {
    if (load_pyodide_exports) {
      return;
    }
    load_pyodide_exports = {};
    init_module();
    let Module = module_exports.Module;
    //... top level contents of load-pyodide.ts
  }
  // ...
  let pyodide_exports;
  function init_pyodide() {
    if (pyodide_exports) {
      return;
    }
    pyodide_exports = {};
    init_load_pyodide();
    let initializePackageIndex = load_pyodide_exports.initializePackageIndex;
    let loadPackage = load_pyodide_exports.loadPackage;
    // ... top level contents of pyodide.ts
    function loadPyodide(config) {
      // ...
    }
    pyodide_exports.loadPyodide = loadPyodide;
  }
  init_pyodide();
  return pyodide_exports;
}
```
Then we could define the public `loadPyodide` as:
```js
function loadPyodide(config){
	let pyodide_exports = exec_module(config);
	return pyodide_exports.loadPyodide(config);
}
```
but I have no clue how to get the bundler to do this.

**Comment by hoodmane** [comment]
> I personally don't have much use case to load multiple pyodide instances yet. But I think it could definitely be something useful. Maybe we could wrap modules and `loadPyodide` in a class `Pyodide` and expose that class. Then every time we instantiate a new instance of `Pyodide`, we create a  new standalone module that does not interfere with other instances.

_Originally posted by @leopsidom in https://github.com/pyodide/pyodide/pull/2220#discussion_r820131453_

**Comment by alexmojaki** [comment]
Being able to create separate instances of a Pyodide class and avoiding global state sounds good, yes. Related to all this is the fact that there seems to be no way to recover from a fatal error in pyodide other than restarting the worker.

**Comment by hoodmane** [comment]
> Related to all this is the fact that there seems to be no way to recover from a fatal error in pyodide other than restarting the worker.

Yeah that's my main concern. Otherwise, starting multiple copies mostly just wastes memory, but there may be some niche uses...

**Comment by hoodmane** [comment]
Okay so on https://github.com/hoodmane/pyodide/tree/multiple-load I have eliminated the rest of the global mutable state and resolved the multiple Pyodides. In order to achieve this, I have to commit some crimes. This is not ready for review but I want to discuss the approach.

We are trapped between constraints imposed by various tools:
1. typedoc only picks up documentation for ES6 exported names. All exports must be top level, so anything we want documented must be top level
2. typescript can't name locally defined classes
3. ES6 module top level state is global (it's scoped to the file, but the program can have at most copy of the file's scope)
4. Almost everything needs access to `API`, `Module`, etc which we want to be local to a specific pyodide instance

The solution to these constraints is that classes and functions are defined at top level (as before) and they access `API`, `Module`, etc via `this`. We then can bind the context into the classes and functions in an `init` function. For a function, binding in the context looks very reasonable. 

This basically means that we shouldn't be using the normal `import` system except for types and for the `init` functions because the imported version won't have the context bound in. 

@leopsidom you have any thoughts on this?

**Comment by leopsidom** [comment]
@hoodmane Sorry just got some time to look at this. The idea of creating a new object and then attach `API`, `Module` etc to the object makes sense to me. Though I'm wondering if there's a better approach to this:

> classes and functions are defined at top level (as before) and they access API, Module, etc via this. We then can bind the context into the classes and functions in an init function.

Instead of binding the context into the class, why can't we pass the initialized `mods` to the class constructor ? Which feels more natural to me. Or is it because of some hard constraints on signature of the class constructors so we have to do it in this way ?

Also it appears we are doing some redundant initialization for instance `init_api` calls `init_module` but in `loadPyodide` we call both methods again. Not sure if this may cause any issue down the road. But if something happens between `init_module` and `init_api`, the change will be lost.

**Comment by hoodmane** [comment]
I redid this on 
https://github.com/hoodmane/pyodide/tree/multiple-load2

>  we are doing some redundant initialization

I put guards in front of each of the `init` methods, but maybe it would make more sense to call all of them once in `pyodide.ts`.

> Instead of binding the context into the class, can we pass the initialized mods to the class constructor ?

Well we never actually call the constructors, we create instances with `Object.create`. We could put the information on the instances, but that would make it impossible to have static methods (which we already don't have).
