### ISSUE TITLE
Power operator incorrect result

### ISSUE THREAD

**Issue by adelattia** [pyodide/pyodide#2482]
## 🐛 Bug

I have an incorrect result when using the power operator ** with some values

### To Reproduce

```print(5 ** 55)```
result : -62726610764649328357466690409063133331

### Expected behavior

```print(5 ** 55)```
result : 277555756156289135105907917022705078125

### Environment

- Pyodide Version: Current demo in browser version (showing python 3.10.2)
- Browser version: Chrome 101.0.4951.41 (Official Build) (arm64)

**Comment by hoodmane** [comment]
Wow thanks for the report.

It's important here that 5^55 is larger than MAX_SAFE_INT = 2^53 which is the largest int such that
```C
((double)x) - 1.0 != (double)x
```
I must have confused the representation of BigInt. Though I'm not sure why type conversions get involved here, this might also be because of an emscripten bug. I wonder if compiling with `-sWASM_BIGINT` makes it go away...

**Comment by ryanking13** [comment]
Thanks for the report. This is huge...

**Comment by ryanking13** [comment]
I am getting the correct results from Python 3.11 alpha 6 REPL of @tiran's (https://cheimes.fedorapeople.org/python-wasm/)

@tiran Do you have any tips on this issue?

**Comment by ryanking13** [comment]
Oh, never mind. It looks like it's our console that is malfunctioning.

![image](https://user-images.githubusercontent.com/24893111/166670312-3c2b1f8c-2be3-4ea5-8efd-cc87836e5b55.png)

**Comment by hoodmane** [comment]
That's good but probably this bug is that python2js misencodes a BigInt so it's not just a repl bug.

**Comment by hoodmane** [comment]
Okay, actually `python2js` translates this correctly. Thanks again to hypothesis for locating several bugs like this that were in the original implementation @ZAC-HD.

So @ryanking13 is right, it is most likely a problem in `console.html`.

**Comment by hoodmane** [comment]
Aha it is a type translations problem but the problem is in the other direction: 
```py
from js import eval
y = eval('277555756156289135105907917022705078125n')
print(y) 
```
should print `277555756156289135105907917022705078125` but instead it prints `-62726610764649328357466690409063133331`

We didn't catch this with hypothesis since we told it not to look for it: `test_number_conversions` specifically restricts to small integers:
```py
integers(min_value=-(2**53), max_value=2**53),
```

**Comment by ryanking13** [comment]
Interesting. Here is another code for minimal reproduction.

```html
<!DOCTYPE html>
<html>
  <head>
      <script src="https://cdn.jsdelivr.net/pyodide/v0.20.0/full/pyodide.js"></script>
  </head>
  <body>
    <script type="text/javascript">
      async function main(){
        let pyodide = await loadPyodide();
		let x = pyodide.runPython(`
			def x(v): return v
			x
		`);
		let v = BigInt(2)**63n;
		console.log("v:", v);
		console.log("x(v):", x(v));
      }
      main();
    </script>
  </body>
</html>
```

```
v: 9223372036854775808n
x(v): -9223372036854775808n
```

**Comment by hoodmane** [comment]
Hypothesis doesn't seem to be able to find it even after 10,000 tries. I guess it's pretty rare.

**Comment by adelattia** [comment]
Wow thank you all for your responses, I'm glad that I found this by accident, thanks to the REPL in the browser :)
Hope someday I could help with coding too :)
