### ISSUE TITLE
Using the gensim module (NLP)

### ISSUE THREAD

**Issue by Amodio** [pyodide/pyodide#2545]
## 🐍 Package Request

- gensim / latest
- https://files.pythonhosted.org/packages/aa/1a/e3a87ee67ffa989438dcf4f113a710335aa95ce96c586c68cac0fa6af0ee/gensim-4.2.0-cp310-cp310-win_amd64.whl

Hello, I am unable to load the gensim module (for doing NLP in the browser) with micropip: `ValueError: 'gensim-4.2.0-cp310-cp310-win_amd64.whl' is not a pure Python 3 wheel`
Is there any solution to fix this or is someone working on including it to pyodide?

Loading another module by URL works on the same host:
```
      async function main() {
        let pyodide = await loadPyodide()
        await pyodide.loadPackage("micropip")
        await pyodide.runPythonAsync(`
        import micropip
        await micropip.install('https://files.pythonhosted.org/packages/ed/dc/c02e01294f7265e63a7315fe086dd1df7dacb9f840a804da846b96d01b96/snowballstemmer-2.2.0-py2.py3-none-any.whl')
        print(micropip.list()) 
      `)
```

Thanks

**Comment by dopplershift** [comment]
The `gensim` wheel you mention is pre-compiled for x86_64 for Windows, while the other wheel (for `snowballstemmer`) only contains Python code. Using `gensim` in pyodide will require [adding it as a package to pyodide](https://pyodide.org/en/stable/development/new-packages.html) so that the C/C++ code in gensim is compiled to Wasm.
