### ISSUE TITLE
Export additional Emscripten modules

### ISSUE THREAD

**Issue by kycutler** [pyodide/pyodide#2577]
## 🚀 Feature

Export Emscripten `Module` in a way that is reliable, or at least a few more of its exports such as `PATH` and `ERRNO_CODES`.

### Motivation

We use [BrowserFS](https://github.com/jvilk/BrowserFS) to help mount custom filesystems into Emscripten. However this requires the `PATH` and `ERRNO_CODES` exports from Emscripten in addition to `FS`.

Pyodide does not currently export these modules in a reliable manner. They can be accessed (currently) via `pyodide._module`, but there is no guarantee this will be reliable across releases.

### Pitch

Ideally, expose the entire Emscripten module in a reliable way so that all of its exports can be accessed. Alternatively, re-export `PATH` and `ERRNO_CODES`.

**Comment by hoodmane** [comment]
> Ideally, expose the entire Emscripten module in a reliable way so that all of its exports can be accessed

This we won't do. The Module has tons of private stuff on it, some of it added by Emscripten, some of it added by us. None of the names on Module are guaranteed stable or intended as public API. Go ahead and use it if it works for your use case but we aren't ever offering stability guarantees about it.

> Re-export `PATH` and `ERRNO_CODES`.

Maybe. Can you give a code example showing how you use them? It's not clear to be from the BrowserFS docs that it is needed.

Due to a bug in Emscripten v2.0.28, the object `Module.ERRNO_CODES` is an empty object so even if we export it, it won't be helpful. We could add `Module.ERRNO_CODES = ERRNO_CODES` to `main.c` and that would probably fix it. I'm not sure if the bug has been fixed in more recent versions of Emscripten. But this illustrates why we don't want to make guarantees about this stuff.

Do you have a workaround to get access to the correct `Module.ERRNO_CODES`?

**Comment by kycutler** [comment]
`PATH` is shown in the example in #613. Not sure why that example is missing the `ERRNO_CODES` but you can see it's used in the `EmscriptenFS` constructor [here](https://github.com/jvilk/BrowserFS/blob/a96aa2d417995dac7d376987839bc4e95e218e06/src/generic/emscripten_fs.ts#L384).

Interesting -- I hadn't noticed that ERRNO_CODES is empty. Basic errors still seem to work in my scenario so it's not clear exactly what functionality this breaks.

**Comment by hoodmane** [comment]
In that case I am +1 for exposing `ERRNO_CODES` and `PATH`. 

For the record the bug looks like this:
```js
var ERRNO_CODES = {}; // Left to fill in later
Module.ERRNO_CODES = ERRNO_CODES;
ERRNO_CODES = { /* actual error codes here */ }
```
They should use `Object.assign` or defer `Module.ERRNO_CODES = ERRNO_CODES` until they have done the second assignment.

**Comment by hoodmane** [comment]
Would you be willing to make a PR? They `ERRNO_CODES` and `PATH` should be moved onto the public API here:
https://github.com/pyodide/pyodide/blob/main/src/js/api.ts#L492
You need to add:
```
/**
 * Comment for API docs
 */
export let ERRNO_CODES;

/**
 * Comment for API docs
 */
export let PATH;
```
just like with FS. 

To work around the `ERRNO_CODES` problem, we should make a file called `post.js` in `src/core` which should read:
```js
Module.UTF8ToString = UTF8ToString;
Module.wasmTable = wasmTable;
Module.ERRNO_CODES = ERRNO_CODES;
```
and add `--post-js src/core/post.js` here:
https://github.com/pyodide/pyodide/blob/main/Makefile.envs#L116

We can then remove the `EM_ASM` block here:
https://github.com/pyodide/pyodide/blob/main/src/core/main.c#L93
