### ISSUE TITLE
Please allow cursor blink to be switched off

### ISSUE THREAD

**Issue by mark-summerfield** [pyodide/pyodide#2620]
When I try the REPL the cursor blinks.

I and a tiny minority of people can't work with blinking cursors. (A tiny minority of lots of people is still a lot.) Please allow blink to be switched off.

See [No blink](https://jurta.org/en/prog/noblink) to see that it isn't just me.

**Comment by hoodmane** [comment]
@jcubic do you have suggestions for this?

**Comment by mark-summerfield** [comment]
Some online REPLs have a cog icon which you can click for configuration options. It would just be a simple [X] Cursor Blink checkbox that's needed.

**Comment by jcubic** [comment]
In recent version of jQuery Terminal I've added a way to disable blinking for people that don't want animations:

```css
@media (prefers-reduced-motion) {
    :root {
        --animation: terminal-none;
    }
}
```

PS: Since you use jQuery Terminal can you maybe link back to my project somewhere on your website?
PPS: How did you solve the issue with async code in Emscipten + jQuery Terminal? Did you use my [PoC/hack](https://gist.github.com/jcubic/87f2b4c5ef567be43796e179ca08c0da) it requires attribution? See the example of how [proper attribution looks like](https://github.com/georgestagg/webR).

**Comment by hoodmane** [comment]
> PS: Since you use jQuery Terminal can you maybe link back to my project somewhere on your website?

Yes we need to add attribution for you for sure. I am sorry we haven't put one in yet, it seems like an important oversight. @rth

> How did you solve the issue with async code in Emscipten + jQuery Terminal?

I believe we have not solved the async code problem, though it is an area of active interest cf #1503.

**Comment by rth** [comment]
> PS: Since you use jQuery Terminal can you maybe link back to my project somewhere on your website?

Sorry about that @jcubic . I added attribution on the REPL page in https://github.com/pyodide/pyodide/pull/2635

**Comment by jcubic** [comment]
Thanks
