### ISSUE TITLE
Specify `pyodide` and its version in `sys.implementation`

### ISSUE THREAD

**Issue by brettcannon** [pyodide/pyodide#2667]
## 🚀 Feature

I think it may be beneficial for `sys.implementation` to reflect Pyodide's details instead of defaulting to what CPython provides.

### Motivation

`sys.implementation` is meant to be an easy way to look up what sort of implementation you're using, what version of that implementation, etc. programmatically. I think Pyodide varies from stock CPython enough to warrant setting the values.

### Pitch

- `sys.implementation.name` is `pyodide`
- `sys.implementation.version` is `0.20.0`

### Alternatives

Leaving things as-is.

### Additional context

We can talk about making CPython to make setting such values easier if need be.

**Comment by hoodmane** [comment]
Grepping for `sys.implementation` in whatever random packages are on my local machine I see:
* lxml/setupinfo.py disables cython compilation if it's not on CPython
* numpy disables certain tests in certain pypy versions
* packaging/packaging/tags.py and packaging/packaging/markers.py
* pip
* A bunch of the vendored copies of packaging package

packaging uses it to compute the wheel tags in `packaging.sys_tags`.  We use `sys_tags` in micropip, so I think if we changed it  we would need to rename our wheels or put a workaround into micropip.
<details>
<summary>Code for packaging.sys_tags</summary>

`interpreter_name()` depends on `sys.implementation.name`:

```py
def sys_tags(*, warn: bool = False) -> Iterator[Tag]:
    """
    Returns the sequence of tag triples for the running interpreter.

    The order of the sequence corresponds to priority order for the
    interpreter, from most to least important.
    """

    interp_name = interpreter_name()
    if interp_name == "cp":
        yield from cpython_tags(warn=warn)
    else:
        yield from generic_tags()

    if interp_name == "pp":
        yield from compatible_tags(interpreter="pp3")
    else:
        yield from compatible_tags()
```
</details>


`lxml/setupinfo.py` has:
```
if hasattr(sys, 'pypy_version_info') or (
        getattr(sys, 'implementation', None) and sys.implementation.name != 'cpython'):
    # disable Cython compilation of Python modules in PyPy and other non-CPythons
    del COMPILED_MODULES[:]
```
I think we also don't want this code to execute. (This is also cross-compilation hostile code since it is a build-time check that assumes the target system is the build system, but that's another issue...)

My feeling from looking at existing code that checks for `sys.implementation == 'cpython'` is that we generally want it to take the branch where they compare equal. So I think it's best to keep it as-is.

**Comment by ryanking13** [comment]
> My feeling from looking at existing code that checks for `sys.implementation == 'cpython'` is that we generally want it to take the branch where they compare equal. So I think it's best to keep it as-is.

I'm +1 with this.

**Comment by brettcannon** [comment]
> I think it would be preferable to phrase that Pyodide is a distribution, not a Python implementation for WASM (as the latter is not true and there is already a lot of user confusion about what's going on in their browser :))

The closest we get to the concept of a distribution is what https://peps.python.org/pep-0514/ specifies in the Windows registry. Would you be interested in distribution name and potentially URL if I were to get exposed in Python somehow?

> That being said, in this particular case, I would also tend to argue that the differences in behavior are due to the wasm32 arch and Emscripten "OS", as [Christian was saying](https://discuss.python.org/t/expected-behavior-for-unsupported-stdlib-modules-in-the-browser/15689/7), though solutions to those constraints might indeed deviate from the standard sdlib behavior.

Right now [it's exposed via `sys.platform`](https://github.com/python/cpython/tree/main/Tools/wasm#detect-webassembly-builds), so if that's the preference on how to detect this I'm also fine with it along with the distributor concept. I guess in my head what CPython upstream produces straight out of a Makefile and what Pyodide produces are not quite the same since Pyodide adds in extra stuff, but right now there's no way to tell the difference programmatically short of whether `import js` works, and I can fake that with a `js.py` file. 😁

**Comment by rth** [comment]
> Would you be interested in distribution name and potentially URL if I were to get exposed in Python somehow?

I think it would be nice to have. There is a somewhat related challenge to know, say on Linux, if the current Python is system installed or e.g. conda installed. There it can be solved by looking at the `sys.executable` path (which we don't have, and it's not fully reliable anyway), and additionally for instance conda-forge [patches of some the CPython files](https://github.com/conda-forge/python-feedstock/blob/main/recipe/brand_python.py) to add this information, probably because there is no better mechanism to do it currently.

Also a bit related to [sys.emscripten_info](https://github.com/python/cpython/blob/8ef7929baffd0038bcb38978a6a91ecc63bf0de2/Python/sysmodule.c#L2690)

> right now there's no way to tell the difference programmatically short of whether import js works,

In this particular case, trying to import `pyodide` is likely the most reliable way. Though yes, it would have been better to have some more systematic mechanism.
