### ISSUE TITLE
RFC Release `pyodide-test-runner` to PyPI

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#2741]
## Proposal

Sometimes I see people who want to test their Pyodide-based applications. So I think it would be great to release `pyodide-test-runner` to PyPI as a standalone package so that people who build applications with Pyodide can easily test their codes.

## Required steps

I think the steps needed for this are:
- [x] 1. Make `pyodide-test-runner` an installable package.
- [ ] 2. Leave only general functions and fixtures (`selenium`, `run_in_pyodide`, ...) inside `pyodide-test-runner` and move other things that will only be used in the Pyodide main repository (`package_is_built`, etc...) into some other place.
- [ ] 3. Write short documentation of using `pyodide-test-runner`.
- [ ] 4. Transfer it to a new repository and release it to PyPI.

## Things need to be considered

One thing we have to consider before transferring `pyodide-test-runner` into a new repository is that Pyodide update should affect `pyodide-test-runner` as less as possible. For example, we have a [code that initializes global hiwire objects](https://github.com/pyodide/pyodide/blob/38fae6e9cbcdd8e932a53bf1c763279dc55729d5/pyodide-test-runner/pyodide_test_runner/browser.py#L174-L194), which is vulnerable to Pyodide API updates. We'll have to move those kinds of code out of `pyodide-test-runner`.

**Comment by rth** [comment]
> Transfer it to a new repository.

 It's a bit orthogonal to releasing to PyPi. I would say we should release to PyPi earlier rather than later. 

About moving it it to a new repo, yes, I can see the appeal. Though, it would make it harder to test changes to this repo, because it would be difficult to run the Pyodide test suite there, but maybe it's indeed the way forward.

**Comment by ryanking13** [comment]
> Though, it would make it harder to test changes to this repo, because it would be difficult to run the Pyodide test suite there

Yes, that is the possible problem. As you say, we can start releasing it to PyPI (when it's ready) without moving it to a new repository.

**Comment by rth** [comment]
Coming back to this, I'm very much in favor of creating a separate package pyodide/pyodide-test-runner. So far the testing setup looks relatively stable and I think it would make the release/update simpler. Otherwise, we would have to add yet another CI job to our already overly complex CI in this repo.

Though we need to decide the naming first #2878
