### ISSUE TITLE
Add "bind" to function PyProxy

### ISSUE THREAD

**Issue by johnwason** [pyodide/pyodide#2757]
## 🚀 Feature

Some libraries like Vue are calling "bind" on functions, to attempt to bind a javascript `this` to the function. Currently, there is no corresponding function in the PyProxy of functions and it is raising an error.

### Motivation

Not having `bind` is causing incompatibility with existing libraries.

### Pitch

Add a `bind` stub, even if it doesn't have any functionality.

**Comment by johnwason** [comment]
It looks like the standard function prototype is cleared here:

https://github.com/pyodide/pyodide/blob/be331255f7dff3011bc8d7127f8ebd0e4db36524/src/core/pyproxy.ts#L149

That is deleting bind and other features.

**Comment by hoodmane** [comment]
Maybe we should just remove that then. We definitely want to get rid of `name` and `length` because otherwise those would cover up common Python attributes. Though I guess it's not so common for a Python callable to have either of these properties. In any case, a Python callable with a `prototype` attribute is probably not common enough to worry about.

**Comment by johnwason** [comment]
I think the expected behavior is that a Python function will behave the same as a JS function using the proxy. Previous versions worked this way. The change of behavior is breaking some of my existing code.

**Comment by hoodmane** [comment]
That line was added in v0.17.0 in this PR:
https://github.com/pyodide/pyodide/pull/1264
