### ISSUE TITLE
"ssl" module not working

### ISSUE THREAD

**Issue by mn3mnn** [pyodide/pyodide#2884]
## 🐍 Package Request

- Package Name and Version : ssl
- Package URL :
- Package Dependencies that needs to be resolved first:

**Comment by tiran** [comment]
May I ask why you are interested in the ssl module? Emscripten does not oiffer traditional sockets and networking support. Pyodide provides different APIs to create HTTPS connections.

**Comment by rth** [comment]
@mn3mnn You should be able to import it with the latest Pyodide version at least. What version are you using and what error are you getting?

@tiran Agreed, but it was requested in https://github.com/pyodide/pyodide/issues/2124 by someone working on a cybersecurity project. Also, openssl [is a dependency of cryptography package](https://cryptography.io/en/latest/openssl/) and many users requested it. So currently `ssl` is an unvendored stdlib module (which depends on `openssl`): it can be loaded but it's not included by default. That's the compromise we found, but we are certainly happy to hear your feedback on this.

**Comment by tiran** [comment]
The smtplib module does not work in Pyodide / Emscripten. The smtplib module uses blocking sockets. Browser environment only support asynchronous, non-blocking sockets. You also can't connect to arbitrary ports from a browser. You would need a helper process on the server side to emulate TCP sockets over WebSockets, see https://emscripten.org/docs/porting/networking.html

**Comment by tiran** [comment]
> @tiran Agreed, but it was requested in #2124 by someone working on a cybersecurity project.

I'm familiar with @skelsec. We have a shared history in security (most friendly). 😎

**Comment by skelsec** [comment]
@mn3mnn as stated by @tiran the above code will not work for multiple reasons. SSL is not one of them.
- you will not have access to the `socket` module, as webassembly itself doesn't have access to sockets
- `smtplib` uses blocking code, this means that even if you could get a connection, the browser would lock up for each `socket.recv` call.
- You probably haven't imported/compiled the `ssl` module in pyodide.  
  
FEAR NOT! for there is a solution to all of these issues:  

- to get sockets working you'd need to either need to build an interface between pyodide and emscripten which provides virtualized sockets using a 3rd party proxy over websockets. OR use my [`wsnet`](https://github.com/skelsec/wsnet) library which is completely undocumented and the API is subject to change at any time. The latter also does require a binary running on the host that provides websockets-socket proxying.
- for smtplib you can use [`aiosmtplib`](https://github.com/cole/aiosmtplib) but you'll need to patch it to use `wsnet` instead of the normal sockets
- use pyodide to compile `ssl` module so you'll be able to import it  
  
It can be done, I managed to get SMB/RDP/Kerberos/LDAP clients crammed into the browser using `wsnet` and `asyncio`.
For a hands-on demo try [`octopwn`](http://octopwn.porchetta.industries/) or if you just wanna get a brief info on how it works check out [`my talk`](https://www.youtube.com/watch?v=jStdrDHTmD4&list=PLv-PXy2JVviu32C4U6F8KHKcyL4s-i_Fo&index=6)

**Comment by tiran** [comment]
Or simpler: Use a service that let's you send emails with a HTTPS REST API or similar. :)

**Comment by mn3mnn** [comment]
@tiran 
I will do that. I am most grateful for your support. 
Thanks.

**Comment by mn3mnn** [comment]
@skelsec 
Thank you for your assistance. Your comment is so helpful

**Comment by rth** [comment]
Thanks everyone for your participation :) Closing as answered (but don't hesitate to comment).
