### ISSUE TITLE
Export version from pyodide JS module

### ISSUE THREAD

**Issue by alexmojaki** [pyodide/pyodide#3068]
## 🚀 Feature

In `pyodide.d.ts` I see `declare let version: string;` but it's not exported. It'd be great if it was exported so that I can do this:

```ts
import {version} from "pyodide";
```

### Motivation

I have [some code](https://github.com/alexmojaki/pyodide-worker-runner/blob/e7dd3d0ee1dff457bf9d6104944477840a83e5a7/lib/index.ts#L16) that roughly looks like this:

```ts
import {loadPyodide, PyodideInterface} from "pyodide";

const version = "0.21.1";
const indexURL = `https://cdn.jsdelivr.net/pyodide/v${version}/full/`;
const pyodide: PyodideInterface = await loadPyodide({indexURL});
if (pyodide.version !== version) {
  throw new Error(
    `loadPyodide loaded version ${pyodide.version} instead of ${version}`,
  );
}
```

I'd like to import `version` instead of setting it manually, so that it always automatically matches whatever version of pyodide is installed.

**Comment by ryanking13** [comment]
Thanks for the suggestion @alexmojaki!

https://github.com/pyodide/pyodide/blob/3e2d7f29a5b242882f2b74bf89319220815136b1/src/js/pyodide.ts#L147

It seems like we are setting the version string of the JS package dynamically during the `loadPyodide` using the version of the Pyodide Python package.

Probably we should have a static version string for JS as you suggested, and maybe we should reject if the requested Pyodide Python package version mismatches JS package version.

**Comment by hoodmane** [comment]
I am in favor of having a static version string. I originally did it this way because we were moving stuff around a lot and we didn't have @ryanking13's `version_bump.py` script so we didn't want to add an extra string we had to update every release (updating the version strings was a major PITA).

In fact it might be a good thing to include the version string in all the files:
1. In `pyodide.js`
2. In `pyodide.asm.*`
3. In `pyodide_py.tar`
4. In `repodata.json` in the .info section.

Then we can be extra paranoid about making sure the files all come from the same version. Usually they do but when there is a mismatch because of e.g., an incorrect partial rebuild on a different branch, if I am unlucky and no error occurs right away it gets really confusing. Most commonly, it would be due to an incorrectly set `indexURL`.
