### ISSUE TITLE
add fiona

### ISSUE THREAD

**Issue by raybellwaves** [pyodide/pyodide#3091]
## 🐍 Package Request

- Package Name and Version : fiona >= 1.8 e.g. 1.8.12
- Package URL : https://github.com/Toblerity/Fiona
- Package Dependencies that needs to be resolved first: Not sure

**Comment by dopplershift** [comment]
GDAL (C++) will be needed first.

**Comment by rth** [comment]
Yes, GDAL would likely be difficult. Though fortunately, it's possible to use Geopandas without fiona at least for GeoJSON format https://github.com/pyodide/pyodide/issues/1569 and likely other file formats in the future https://github.com/geopandas/geopandas/issues/2548#issuecomment-1242702730

**Comment by ryanking13** [comment]
fiona and geopandas is now added (#3213). If you have trouble using it, feel free to open a new issue.

**Comment by MarcSkovMadsen** [comment]
Due to a request from Moving Pandas here https://discourse.holoviz.org/t/try-out-panel-sharing/4549/5 I just tried to install fiona and geopandas in the pyodide console via micropip. But it fails. Should I open a new issue @ryanking13 ?

![image](https://user-images.githubusercontent.com/42288570/201507244-72856526-1674-47f4-aa6a-6008f0284b00.png)

Also the test in #3213 fails https://ryanking13.github.io/geopandas-pyodide-test/

![image](https://user-images.githubusercontent.com/42288570/201507302-0cacb6d8-6d15-4b12-adad-05fe4bc00825.png)

FYI. @raybellwaves

**Comment by ryanking13** [comment]
I guess it is answered in #3248? (I also fixed the URL in my example repo, thanks for the report!)
