### ISSUE TITLE
Move micropip to a separate repo in the org

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#3093]
Continuing with the effort of making the code base more approachable (https://github.com/pyodide/pyodide/issues/2014), I would propose to move micropip to a separate repo in the Pyodide org.

### Advantages 
 - mich faster iteration cycle to change anything in micropip. CI should take minutes not an hour as currently.
 - for new contributors, it's also much easier to start since it's a pure Python package they don't need to deal with the rest of the build system.
 - can update micropip for a given Pyodide release by loading the pure Python wheel from PyPi with `pyodide.loadPackage`. The release schedule of micropip can become independent from Pyodide.
 - there are several other projects in this space (e.g. emscripten-forge, https://github.com/ethanhs/python-wasm) and this would make it  easier to reuse and contribute back fixes if necessary. There is still the FFI question which is more difficult, but right now even if emscripten-forge wanted to support installing Pyodide packages (and assuming  binary compatibility) they have no other way short of vendoring it. Similarly, I'm hoping this could encourage some of the micropip related fixes from JupyterLite to be contributed upstream.

### Advantages 

- a bit more setup work, but we have done this for a lot of packages now, so it's mostly copy-pasting
- makes it harder to make large changes across different components of Pyodide, though I think micropip is pretty stable now and there are rarely PRs that need to change both the internals and micropip at the same time.

**Comment by bollwyvl** [comment]
What `piplite`/`jupyterlite` hacks are wanted? Happy to shed some stuff!

Even if _all_ our hacks weren't desirable, it would be lovely to have a few more documented ways to customize micropip, rather than trying to solve some things Once And For All... presenting the two together:

- handling multiple package sources
  - we [check](https://github.com/jupyterlite/jupyterlite/blob/main/packages/pyolite-kernel/py/piplite/piplite/piplite.py#L65) for a custom Warehouse (or [warehouse-like](https://github.com/pypi/warehouse/blob/main/warehouse/legacy/api/json.py#L96) [file format](https://jupyterlite.readthedocs.io/en/latest/_static/pypi/all.json)) for custom/offline packages
  - notionally, `micropip.add_pypi_json_resolver(key: str, get_pypi_json: Callable[[str, dict], PackageReleases])`
- disabling package sources
  - for offline (but still dynamic) installations, it's nice to have some guardrails in place to avoid calling out to Big PyPI
  - notionally, `micropip.remove_pypi_json_resolver(key: str)`
- specifying no-op packages to be considered installed
  - not handled in `piplite`, but rather in separate build packages
  - notionally, `micropip.add_noop_package(package_name: str)`

Some things that we hack outside of `piplite`, so maybe they belong in core:
- specifying patches that need to occur at import time
  - we [un-lazily load and patch](https://github.com/jupyterlite/jupyterlite/blob/main/packages/pyolite-kernel/py/pyolite/pyolite/patches.py) some heavy hitters (`matplotlib`, oy!)
  - this is really more of a loader-time thing, so maybe should be a `pyodide` API
  - we tried to use some off-the-shelf stuff, but at some point it stopped working
- specifying mock packages
  - we [mock](https://github.com/jupyterlite/jupyterlite/blob/main/packages/pyolite-kernel/py/pyolite/pyolite/mocks.py) some packages

**Comment by hoodmane** [comment]
This may be a bit off topic, but someone published `micropip` to pypi:
https://pypi.org/project/micropip/
We should probably ask them to transfer it to us.

**Comment by rth** [comment]
> What piplite/jupyterlite hacks are wanted? 

Thanks for the summary @bollwyvl ! Maybe let's first move it to a separate repo (if this proposal is supported), and open issues for it, to take it one step at a time. But yes a lot of those sound interesting! I'll keep the list in mind once we get there.

> We should probably ask them to transfer it to us.

I sent an email.

**Comment by rth** [comment]
I created https://github.com/pyodide/micropip and this will be resolved with https://github.com/pyodide/pyodide/pull/3122
