### ISSUE TITLE
Stdout not ending in newline doesn't trigger stdout callback until newline is printed

### ISSUE THREAD

**Issue by obfuscatedgenerated** [pyodide/pyodide#3112]
## 🐛 Bug

When the Python code prints to stdout some text not ending with a new line, the stdout callback configured in loadPyodide() isn't called.

### To Reproduce

```js
let py = await loadPyodide({
        stdout: (data) => {
            console.log(`Got stdout data: ${data}`);
        }
});


py.runPython(`print("Hello world!", end="")`); // this doesn't call the stdout callback
py.runPython(`print("\n")`); // until this happens
```

### Expected behavior

This should call the stdout event as soon as text is put. Once for putting `Hello world!`, then once for putting new line. Some devs may prefer it only called on newline prints, but I need to use the output. Could be an configurable option? After all, this would probably be a breaking change in some projects.

### Environment

- Pyodide Version: `0.21.2` loaded in browser with JSDelivr, with type interfaces over npm (not included in built website)
- Browser version: Chrome 105.0.5195.127
- Any other relevant information: Using Typescript and Webpack (with pyodide set as an external to load via JSDelivr)

### Additional context

There may be other functions that write to stdout like this, but print() is the most prominent example.

*Cheers!*

**Comment by hoodmane** [comment]
This is an annoying issue. The reason is that the default `stdout` and `stderr` is `console.log` and `console.warn` and these cannot print partial lines. So the emscripten helper functionality for this is written with the assumption that the streams will similarly only want complete lines. Eventually we should get make a fix. Another issue that comes up is declaring whether `isatty` should be True or False, which it should be possible to declare separately. Currently `isatty` defaults to `True` but becomes `False` if you pass a custom handler. It should really default to `False` since `console.log` can't act like a tty. If the user passes their own handler, they should get to declare if it should be atty or not.

The following code fixes this in the meantime:
https://github.com/pyodide/pyodide/blob/main/tools/python#L94

**Comment by hoodmane** [comment]
@sbc100

**Comment by obfuscatedgenerated** [comment]
Hello, workaround works great! Hopefully there'll be a more official solution in 0.22.0 as you say. Thanks for the help 😁
