### ISSUE TITLE
The content area in the docs is too narrow

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#3135]
## 📚 Documentation

In the documentation strings, rendered code examples only fit 63 characters of width. It would be nice if we could make the content area a bit larger so that code examples fit at least 80 characters. On my screen, the content area is exactly the middle third of the screen, with the left and right thirds devoted to menus.

**Comment by ryanking13** [comment]
Sounds good to me. It looks like we had wider area in [0.18.0](https://pyodide.org/en/0.18.0/usage/quickstart.html).

**Comment by hoodmane** [comment]
Yes that's way better. I wonder what changed.

**Comment by jobovy** [comment]
You might need to add
```
panels_add_bootstrap_css
```
to the ``conf.py`` file? See

https://sphinx-panels.readthedocs.io/en/latest/#sphinx-configuration

and 

https://github.com/executablebooks/sphinx-book-theme/issues/194#issuecomment-697028667

``sphinx_panels`` was added in #1960, so that seems consistent with when the width changed... I can't test this locally though, because I can't easily get the docs to build.

**Comment by hoodmane** [comment]
> because I can't easily get the docs to build.

Maybe that should be a separate issue. I agree that building the docs locally is a bit of a pain.

**Comment by hoodmane** [comment]
> add `panels_add_bootstrap_css= False`

This fixes the problem, thanks @jobovy!
