### ISSUE TITLE
Infinite prompt by using an input in v0.22.0

### ISSUE THREAD

**Issue by nicobytes** [pyodide/pyodide#3413]
## 🐛 Bug

When I'm using `input` with the new version, show an prompt in infinite mode.

### To Reproduce

`input('Type text')`

### Expected behavior

Display the alert only once. 

### Environment

- Pyodide Version : 0.22.0

### Additional context

https://www.loom.com/share/08ccfbf98afc43a984feb4eccfd53d3f

**Comment by rth** [comment]
Thanks for the report @nicobytes, I can reproduce in the REPL as well! Likely due to the changes in stdin handling cc @hoodmane 

Also actually it looks like we don't currently have a test for default `input()` filled via an alert? Although it would indeed be a bit more tricky to test. The closest we have is [this one](https://github.com/pyodide/pyodide/blob/main/src/tests/test_pyodide.py#L1118)

**Comment by rth** [comment]
@hoodmane Any ideas about this?
