### ISSUE TITLE
[Discussion] Unvendor deep-frozen stdlibs?

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#3524]
Thanks to the hard work of Hood, we now run Python 3.11.

One big, but not very well-known change in CPython 3.11 is that it started to deep-freeze some of the standard libraries, i.e. compile python source codes into C and statically link them to libpython. According to cpython docs, a ["significant performance improvements to startup"](https://docs.python.org/3/whatsnew/changelog.html#id123) is achieved by this deep-freeze.

However, the trade-off is that it increases the bundle size, which is a crucial factor for us.

```sh
# 0.22.1 (Python 3.10.2)
7.2M pyodide.asm.wasm

# 0.23.0a1 (Python 3.11.1)
8.6M pyodide.asm.wasm

# Python 3.11.1 without freezing stdlibs except for importlib, zipimport
# (https://github.com/ryanking13/pyodide/tree/unfreeze)
7.9M pyodide.asm.wasm
```

So I would like to discuss some possible options:

1) No change.
2) Disable deep-freezing modules. This will reduce the size of pyodide.asm.wasm, but we cannot get the advantage of bootstrap optimization. This will also make it hard to do #3166.
3) Unvendor or remove python source codes of deep-frozen modules. This will reduce the size of pyodide.asm.data, so we can reduce the total download size increase. Users will not be affected (I guess...?) unless they try to access the source code of the frozen modules.

I would like to suggest option 3. Any ideas are welcome.

WDYT?

**Comment by hoodmane** [comment]
Thanks for opening this issue @ryanking13. Option 3 sounds good to me. I would prefer the unvendor option so we could allow some `loadPyodide` setting to download all of these at startup. It might be nice if we could come up with some way to adjust the behavior of the `inspect` module so that it can tell people how to get the missing source code, though not if this is too much work.

**Comment by rth** [comment]
> a ["significant performance improvements to startup"](https://docs.python.org/3/whatsnew/changelog.html#id123) is achieved by this deep-freeze.

I would say it would be good to benchmark to see to what extent it's true for us. In their benchmarks, they didn't have to compile WASM code. So while in general, more C code tends to be faster, in our case it might very well make things slower because of increased compile time. Hard to say without measuring it.

For the size I wouldn't say it's that critical, what matters IMO is the compressed size of pyodide.asm.wasm which was 2.53 MB for 0.22.1 and is 2.87 MB  for `main` so it's pretty small difference.  

Can you explain again the link between this deepfreezing or not and https://github.com/pyodide/pyodide/pull/3166 ? I though that we could do that unrelated to deepfreezing, but I might have missed something.

**Comment by rth** [comment]
Here are the benchmarks with firefox Profiler which seems to auto-generate sharable links now,
 - [Pyodide dev (with deepfrozen modules)](https://profiler.firefox.com/public/jxq98tnxybtjmg4s6ce2majgvxam3cpmy1vfgag/calltree/?globalTrackOrder=01&implementation=js&profileName=Pyodide%20dev%20benchmark&thread=2&v=8) - loadPyodide takes 6,554ms. 
 - [Pyodide 0.22.1 (without deepfrozen modules)](https://profiler.firefox.com/public/vdcvcbb244zc9j41s9gpswjwxbgdhtzjextvcn8/calltree/?globalTrackOrder=01&implementation=js&profileName=Pyodide%200.22.1%20load%20benchmark&thread=2&v=8)  -loadPyodide takes  6,456ms
 
This is with caching disabled in the network tab, so network transfers are part of it (but with a fast internet connection they are close to negligible I think).  And of course, many other changes were done in py 3.11 so it's not a very reliable benchmark for deepfreezing. It would be interesting to re-run the profiling before/after https://github.com/pyodide/pyodide/pull/3539. Still, it seems to indicate that overall load time is more or less the same between py310 and py311.

To get those profiles in Firefox, I just load the REPL, disable cache in the network dev console tab, in the profiler tab click on "Start recording", reload the page, then click on "capture recording".  Not sure it's the best way to profile but it seems to work. Then if you want a sharable profile link, you need to click on "Upload local profile" on the new page that is opened.

I guess my point is that because we have such a non standard runtime env, we cannot really trust any performance related benchmarks done in CPython and need to re-run them in the browser to confirm.

**Comment by ryanking13** [comment]
@rth Thanks for the benchmark! Yeah, our environment is quite different from native environments and we can't just trust the CPython benchmarks.

> Can you explain again the link between this deepfreezing or not and [#3166](https://github.com/pyodide/pyodide/pull/3166) ? I though that we could do that unrelated to deepfreezing, but I might have missed something.

Sure, actually, my explanation was not enough. What I want to do is:

1) Split out python standard libraries from pyodide.asm.data into a zip file e.g. `python311.zip`.
2) During `loadPyodide`, download this zipfile and save it to the file system. Which is similar to what we do for `pyodide_py.tar`.

By doing this, we can achieve the followings:

- deploy both compiled and not-compiled standard libraries and let users choose which one to use
- users can add to or remove from anything to standard libraries, which might be useful for `pyodide-pack`.

The problem is that, in this case, the source code of standard libraries is not available during the Python bootstrap stage. Python requires a portion of standard modules like `os, sys, importlib, encodings` during the bootstrap stage, therefore it raises an error when these modules are not available. Deep-freezing modules can help fix this situation by compiling and linking these modules to libpython, which makes it available to use these modules without the source code.

**Comment by hoodmane** [comment]
It would be nice if we could only deep freeze the part of encodings needed to start the interpreter. It's a pretty large module and large parts of it I suspect are not used in a lot of code. It would be particularly great if users could just load the encodings they need. But this is a longer term goal.

**Comment by ryanking13** [comment]
> It would be nice if we could only deep freeze the part of encodings needed to start the interpreter.

That would be nice, I'm not sure what would happen if I only deep-freeze `__init__.py` of encodings module. I guess I will have to try.

**Comment by hoodmane** [comment]
I think you will need more than just `__init__.py`. But probably `__init__.py`, `aliases.py`, and `utf_8.py` are enough:


```
$ python3.11 -v -c "print('hello')" 2>&1 | grep "import 'encodings"
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb4308cde10>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb4308be290>
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb4308bfc10>
```

**Comment by hoodmane** [comment]
The whole encodings module is 1.7 mb uncompressed, but the three files that are needed for startup are more like 22kb.

**Comment by ryanking13** [comment]
Closing as it's not worth the effort.
