### ISSUE TITLE
[Package request] Pyshorteners

### ISSUE THREAD

**Issue by ndonkoHenri** [pyodide/pyodide#3530]
## 🐍 Package Request

- Package Name and Version : **Pyshorteners / latest**
- Package URL : https://pyshorteners.readthedocs.io/ | https://pypi.org/project/pyshorteners/
- Package Dependencies that needs to be resolved first:

**Comment by ryanking13** [comment]
The pyshorterners looks like a pure Python library, so could you please try to build a wheel and use it directly? Since it requires `requests`, probably you would also need to patch it with e.g. [pyodide-http](https://github.com/koenvo/pyodide-http).

**Comment by ndonkoHenri** [comment]
Sorry, but I'm not that of a great dev 😅
I was using [Flet](https://flet.dev) and got this error when hosting my app: 
https://media.discordapp.net/attachments/1000264673284857866/1070385731941437600/image.png

I was then asked by a dev in Flet to suggest the addition of that package here. (They deploy apps to the web with the help of pyodide..)

**Comment by ryanking13** [comment]
Building a wheel is quite easy:

```
wget https://files.pythonhosted.org/packages/80/13/7dd5f53ac009775e18861f41efadf78160e1015c84a476d373957cb63b5c/pyshorteners-1.0.1.tar.gz
tar -xf pyshorteners-1.0.1.tar.gz
cd pyshorteners-1.0.1
pip install build
python -m build .
```

After this, you'll need to serve the built wheel in some place though.

Otherwise, you can also ask the maintainer of `pyshortners` to add a wheel in PyPI.

**Comment by ndonkoHenri** [comment]
Ok. Could you please give me an example of a place I could serve it on? 
And also, what about the `requests` you mentioned above?

**Comment by ryanking13** [comment]
> Ok. Could you please give me an example of a place I could serve it on?

One easy way is to put a wheel on GitHub. For example, I uploaded a wheel [here](https://github.com/ryanking13/geopandas-pyodide-test/blob/main/pyodide/geopandas-0.11.1-py3-none-any.whl), then you can access it via https://raw.githubusercontent.com/ryanking13/geopandas-pyodide-test/main/pyodide/geopandas-0.11.1-py3-none-any.whl.

Note that this is easy but not a very great idea regarding performance since Github is not a CDN, so the download speed will vary across countries.

> And also, what about the requests you mentioned above?

It seems like the pyshortners have a dependency on `requests`. Due to [browser limitations](https://pyodide.org/en/stable/project/roadmap.html#write-http-client-in-terms-of-web-apis), `requests` is not available in Pyodide.

Pyodide provides an alternative way to send requests using browser APIs like `XMLHttpRequest` and `fetch`, and pyodide-http is a library that provides a patch which patches `requests` and `urllib` with browser APIs.

**Comment by ndonkoHenri** [comment]
Thank you for this clear and concise explanation.
Concerning the request stuff, what do you want me to do concretely? Go in pyshorteners lib and modify all areas using `requests` to instead make use of `pyodide-http`?

**Comment by ryanking13** [comment]
You can start with trying the way mentioned in [pyodide-http docs](https://github.com/koenvo/pyodide-http):

```py
# 1. Install this package
import micropip
await micropip.install('pyodide-http')

# 2. Patch requests
import pyodide_http
pyodide_http.patch_all()  # Patch all libraries
```

In ideal situation, `pyshortners` will "just work" with this few lines of code. If not, you'll have to find which part is not working and start debugging.

**Comment by rth** [comment]
Closing as from the above discussion it sounds like there is a need to include this package in Pyodide.

If you experience any issues building the wheel or using `pyodide-http` (or any other questions) don't hesitate to comment though.
