### ISSUE TITLE
GH Actions are broken for main branch

### ISSUE THREAD

**Issue by tubaman** [pyodide/pyodide#3601]
## 🐛 Bug

The GH Actions aren't passing for the main branch.
The following stages are failing:

   * [lint](https://github.com/pyodide/pyodide/actions/runs/4236786417/jobs/7361997963)
   * [CircleCI](https://app.circleci.com/pipelines/github/pyodide/pyodide/5351)

### To Reproduce

I've created a PR with a trivial change here: #3600 

### Expected behavior

I expect the GH actions to all pass on the main branch so that actions on PRs shows what's broken about the PR.

### Environment

Commit hash of Pyodide git repository: main branch (862e4f8877de00028ba8c4b1200e7e8e914cf1ae)
Build environment: GH actions

**Comment by rth** [comment]
For the linting job, I don't know why it failed on the last commit, particularly given that the pre-commit.ci which runs the same linting passed. Rather than investigating, I think we can remove it as it's redundant with pre-commit.ci, and as far as I can tell no other CI job needs it.

About the other issue, it's a known CircleCI OAuth issue for some users https://github.com/pyodide/pyodide/issues/3492 that we still have no good solution for.

**Comment by ryanking13** [comment]
+1 for removing it.

**Comment by ryanking13** [comment]
Actually, pre-commit.ci started to fail with the same error.
