### ISSUE TITLE
tiktoken need to be compiled into wasm

### ISSUE THREAD

**Issue by mccoysc** [pyodide/pyodide#3875]
https://github.com/openai/tiktoken.
in fact,its file "lib.rs" is easy to be compiled to wasm.
so it can be supported?

**Comment by mccoysc** [comment]
@rth

**Comment by mccoysc** [comment]
@hoodmane

**Comment by psymbio** [comment]
@mccoysc 

Hi, you can look at this wasm I've created here: https://github.com/psymbio/tiktoken_rust_wasm/blob/main/packages/build_emscripten/tiktoken-0.5.1-cp311-cp311-emscripten_3_1_45_wasm32.whl

However, there are some issues with the "requests" library.

**Comment by rth** [comment]
Thanks for investigating this @psymbio !

If you do,
```py
import micropip
await micropip.install("https://cdn.jsdelivr.net/gh/psymbio/tiktoken_rust_wasm/packages/build_emscripten/tiktoken-0.5.1-cp311-cp311-emscripten_3_1_45_wasm32.whl")   # loading from github via jsdelivr to set CORS headers
await micropip.install("pyodide-http")

import pyodide_http
pyodide_http.patch_all()
import tiktoken
enc = tiktoken.get_encoding("cl100k_base")
```
you would get a `pyodide.ffi.JsException: NetworkError: A network error occurred.` and in the browser developer tab the actual reason is that when loading
```
https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken
```
it fails due to "CORS Missing Allow Origin" error message. So this server needs to set CORS for this data to be loadable from a web page.

The solution could be,
 - either to ask OpenAI to add CORS headers there (also applicable to anyone wanting to use tiktoken from JavaScript)
 - or to patch the URL to use a CORS proxy (there are a few free ones if you search).

**Comment by psymbio** [comment]
Thanks for getting back @rth!

Yes, CORS error. For now obviously don't imagine OpenAI wanting to change their CORS headers so this is what I came up with is basically caching anything that is needed by the requests library and creating a new wheel here is the wheel file: https://github.com/psymbio/tiktoken_rust_wasm/blob/main/packages/build_emscripten_cached_weights/tiktoken-0.5.1-cp311-cp311-emscripten_3_1_45_wasm32.whl and to check if it works here: https://github.com/psymbio/tiktoken_rust_wasm/blob/main/index.html

You can check the steps I've taken to do this: https://github.com/psymbio/tiktoken_rust_wasm and https://github.com/psymbio/tiktoken (still some fixes needed - will do it in a few days).

I think it would be interesting to look at a generalized solution for different packages with the same roadblock.
