### ISSUE TITLE
Re-enabling sparseqr in pyodide ?

### ISSUE THREAD

**Issue by gabrielfougeron** [pyodide/pyodide#3941]
## 🐛 Bug

A few weeks back you guys re-enable sparseqr in pyodide. Cf #3783 and #3781 .
Yesterday, you released version 23.3. Using the REPL today, I wasn't able to load sparseqr.

![image](https://github.com/pyodide/pyodide/assets/8499652/fce218c1-520e-4fdc-b581-ebf9cef820fb)

Am I missing something ?

**Comment by rth** [comment]
It looks like it was not backported into 0.23.3 (at least it's not in [repodata.json](https://cdn.jsdelivr.net/pyodide/v0.23.3/full/repodata.json)). Because 0.23.X is a different branch, anything merged in main doesn't automatically end up in patch releases. So for now you would need to use the dev deployment (and [dev REPL](https://pyodide.org/en/latest/console.html)).

**Comment by gabrielfougeron** [comment]
Thank you @rth for those explanations 😊😊😊

**Comment by hoodmane** [comment]
Yeah we probably should have backported it...

**Comment by gabrielfougeron** [comment]
No worries, I was simply confused 😊👍
