### ISSUE TITLE
When Using Pyfetch meet CORS Error

### ISSUE THREAD

**Issue by Jimmy-web169** [pyodide/pyodide#4060]
Hi When I Using Pyfetch request an API, It will cause CORS ERROR，How can I fix it

**Comment by ryanking13** [comment]
If you are the owner of the server sending the request, you can include the CORS header in the server's response. If not, you'll probably need to use a CORS proxy server to create and send a CORS response in the middle.

Note that there is nothing Pyodide itself can do about the CORS issue, because it is a browser limitation. Closing this as answered but don't hesitate to comment more if you have more questions.
