### ISSUE TITLE
Function signature mismatch: random_multinomial

### ISSUE THREAD

**Issue by allsey87** [pyodide/pyodide#4083]
Something to be checked. I am getting a warning when I try to statically link NumPy to Pyodide. It works fine, but this should probably be checked/fixed if there are indeed two conflicting definitions for `random_multinomial`.

```
wasm-ld: warning: function signature mismatch: random_multinomial
>>> defined as (i32, i64, i32, i32, i32, i32) -> void in dist/libnumpy.a(_generator.o)
>>> defined as (i32, i32, i32, i32, i32, i32) -> void in dist/libnumpy.a(distributions.o)
```

**Comment by hoodmane** [comment]
Interesting. Thanks for the report! I see that `numpy/random/c_distributions.pxd` has the second argument declared as `int64_t n` but in `numpy/core/include/numpy/random/distributions.h` it is declared as `RAND_INT_TYPE n`. Perhaps `RAND_INT_TYPE` is pointer sized and so this is incorrect on 32 bit platforms?

**Comment by hoodmane** [comment]
Sure enough, `_generator.o` imports `random_multinomial` with type `(i32, i64, i32, i32, i32, i32) -> nil` and `distributions.o` defines it with type `(i32, i32, i32, i32, i32, i32) -> nil`. It seems to be that the type of `RAND_INT_TYPE` is controlled by the environment variable `NP_RANDOM_LEGACY`. If `NP_RANDOM_LEGACY` is defined to be 1, then it's defined to be `long` which is probably 32 bits on wasm32. Otherwise, it's defined to be `int64`. But `numpy/random/c_distributions.pxd` unconditionally declares it as `int64`. This is probably best regarded as a bug in numpy.

**Comment by allsey87** [comment]
Closing in favour of https://github.com/numpy/numpy/issues/24490

**Comment by hoodmane** [comment]
Thanks so much for reporting this @allsey87!
