### ISSUE TITLE
Unclear loadPyodide({ packages }) behavior

### ISSUE THREAD

**Issue by WebReflection** [pyodide/pyodide#4152]
## 📚 Documentation

Apparently there is a new `packages` options that accepts a list of strings when `loadPyodide` is invoked but what I've observed is:

  * if I pass packages I am meant to install via `micropip` it breaks
  * if I pass `['micropip']` as opposite of `await interpreter.loadPackage('micropip')` there is no error **but** I still need to `await interpreter.loadPackage('micropip')` for packages otherwise it breaks

Is it possible I am doing something wrong but from the docs it's really unclear how one could benefit from this new option.

Thanks in advance for any kind of explanation.

**Comment by rth** [comment]
Yes, as far as I understand (though I wasn't involved in https://github.com/pyodide/pyodide/pull/4100 that added it), this intentionally only works with packages distributed by Pyodide. If you need PyPI packages you can indeed add micropip and then install them with micropip. 

The idea is that it's an optimization option. If you have an application with a given set of dependencies, you can then generate `pyodide-lock.json` with `micropip.freeze()` and then use this option.

But I agree we should document this better. 

We could maybe consider installing micropip if the requested package is not `pyodide-lock` and trying to install with micropip. Though then it doesn't wouldn't seem like a very robust behavior, which is why we have not done it so far. But also agree that the current situation might be confusing for us (due to this loadPackage / micropip.install difference).

**Comment by WebReflection** [comment]
@rth one confusing thing per time :D ... should I pass `['micropip']` to `loadPyodide({ packages })` ??? it seems to require `await interpreter.loadPackage('micropip')` later on regardless of me passing it already or not, while I would at least expect that I don't need to explicitly load it after, unless currently passing it before means it loads it faster? This is the most confusing part to me, thanks!

**Comment by WebReflection** [comment]
Actually ... it looks like you do that internally too: https://github.com/pyodide/pyodide/pull/4100/files#diff-29094eee939ca221ba2ac25283c87ae106b6d5984b84decb097cbc93dd52e455R518-R519

so I guess there is some confusion about wording there ...

> **options.packages** ([string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String)[]) – A list of packages to load as Pyodide is initializing. **This is the same as loading the packages with [pyodide.loadPackage()](https://pyodide.org/en/stable/usage/api/js-api.html#pyodide.loadPackage) after Pyodide is loaded** (it's not, one still needs to `loadPackage` even if the packages was passed to the `loadPyodide`) except using the packages option is more efficient because the packages are downloaded while Pyodide bootstraps itself.

Do we agree something is off with the docs page and the current behavior which is also what it's tested?

**Comment by WebReflection** [comment]
OK, it looks like I had a different issue and wrongly blamed this feature ... basically I have *matplotlib* breaking with Pyodide 0.24.0 so it wasn't about how I was loading it, it was something else ... I have tried then to use Pyodide 0.24.0 and simply skip the `loadPackage('micropip')` dance and indeed that seems to work fine, numpy is imported, ence available within the script.

Apologies for (my) confusion, eventually there should be a bug about matplotlib breaking in latest Pyodide, but that's another story.

**Comment by rth** [comment]
No worries, we can still probably add a few more details to the docs on this feature.

**Comment by hoodmane** [comment]
At least we should remove `await pyodide.loadPackage("micropip")` from that test...
