### ISSUE TITLE
`dict_converter=Object.fromEntries` does not work with the default converter

### ISSUE THREAD

**Issue by pfebrer** [pyodide/pyodide#4260]
## 🐛 Bug

This screenshot in the pyodide terminal (https://pyodide.org/en/stable/console.html) explains the bug:

![Screenshot from 2023-10-27 11-29-33](https://github.com/pyodide/pyodide/assets/42074085/b3b2e9f8-5483-4496-8c84-b8fd2ef7ae77)

Here is the full script to reproduce the error:

```python
from pyodide.ffi import to_js
from js import Object

# The default converter just returns a dictionary
def default_converter(obj, c, _): return c({"a": 2})

# Create a class that is not convertable to js
class A: pass

# Convert to js, converting dicts to maps
to_js(A, default_converter=default_converter) # This is ok

# Convert to js, converting dicts to objects
to_js(A, dict_converter=Object.fromEntries, default_converter=default_converter) # This is not ok
```

### Expected behavior

I would expect that it worked with `Object.fromEntries` as well.

### Environment

- Pyodide Version: Python 3.11.3 (main, Sep 25 2023 20:45:01) on WebAssembly/Emscripten (also on pyodide `0.24.1`).
- Browser version: Brave [Version 1.31.91 Chromium: 95.0.4638.69] and Chrome [Version 118.0.5993.88]

**Comment by hoodmane** [comment]
Thanks for the report @pfebrer! I can reproduce it. 

I investigated a bit and I'm perplexed. I've chased the trouble back to the following code:
```C
    context.jscontext = python2js_custom__create_jscontext(
      context, cache, dict_converter, default_converter);
```
and in the generated code I see:
```wat
          ;; collect args
          local.get $var6
          local.get $var3
          local.get $var4
          call $python2js_custom__create_jscontext
          i32.store offset=88
```
which stores the result at offset 88 from `context`.  The struct for `context` looks like:
```C
typedef struct
{
  JsRef cache;
  int depth;
  JsRef proxies;
  JsRef jscontext;
  // more fields omitted
} ConversionContext;
```
`JsRef` is pointer sized, so 4 bytes. If we count the offset, we see that `jscontext` is at offset 12. But the generated code stores the `jscontext` at offset 88 which is... somewhere else ... and then the `jscontext` field is later read back as `NULL` which causes the crash. But what I can't understand is why the following:
```py
to_js(A, default_converter=default_converter) # This is ok
```
would work since it also goes through this code. Also how did the compiler generate the offset 88? Very perplexing. I'll have to investigate further...

**Comment by hoodmane** [comment]
Okay I understand what's happening: I am passing `context` by value, when I should be passing `&context`. In the wasm calling ABI, nonsmall structs are passed on the stack. Sometimes the compiler places the `context` argument in the same location on the stack as the `context` return value so the two structs are aliased and then it behaves okay. Because `python2js_custom__create_jscontext` is an `EM_JS` function I am manually responsible for respecting the ABI but I'm not properly respecting it so there's undefined behavior.

**Comment by pfebrer** [comment]
Before posting I investigated a little `pyodide`'s source code and I concluded that it was impossible for me to fix it. You just confirmed it hahaha

Thanks for the explanation!

Is it fixable then?

**Comment by hoodmane** [comment]
Yes it's a pretty simple patch =)
