### ISSUE TITLE
Python 3.12 version

### ISSUE THREAD

**Issue by liudonghua123** [pyodide/pyodide#4420]
## 🚀 Feature

Hi, I tried [REPL](https://pyodide.org/en/stable/console.html), maybe it uses the latest 0.25.0, and I noticed that the python is 3.11.3.

Python 3.12 has released for a few months with a lot of new features. Since there is no issue track the progress. So, I created this one.

### Motivation

N.A.

### Pitch

N.A.

### Alternatives

N.A.

### Additional context

N.A.

**Comment by hoodmane** [comment]
Generally we aim to wait about six months after a new Python release comes out before updating, so since the Python versions are released in August, we usually do the update in February / March. This reduces the number of broken packages that we have to deal with in the update. Anyways it's about time to start working on this.

**Comment by liudonghua123** [comment]
@hoodmane Thanks, I see. 😃

**Comment by hoodmane** [comment]
@liudonghua123 I released Pyodide 0.26.0a1 with Python 3.12 so you can try it out if you like.

**Comment by hoodmane** [comment]
Hmm actually looks like release pipeline failed, I'll have to retrigger it.

**Comment by liudonghua123** [comment]
Thanks for the perfect work. I will try it.
