### ISSUE TITLE
Package request: polars

### ISSUE THREAD

**Issue by luiscastro193** [pyodide/pyodide#4611]
## 🐍 Package Request

- Package Name and Version : polars / latest
- Package URL : https://github.com/pola-rs/polars
- Package Dependencies that needs to be resolved first:

Polars supports a wasm target already so it shouldn't be too hard. Also, scikit learn is planning on moving from Pandas to Polars as their [default dataframe lib](https://github.com/scikit-learn/scikit-learn/issues/28341) so it seems relevant.

**Comment by georgestagg** [comment]
I'm taking a shot at this. More info at https://github.com/dtolnay/inventory/issues/71#issuecomment-2391782635 and https://github.com/llvm/llvm-project/pull/111008#issue-2564381414.

Using a fork of LLVM, a custom `rustc`, disabling a bunch of features in Polars, and making some patches for wasm32 & Emscripten - (my patches are at [georgestagg/polars@emscipten](https://github.com/georgestagg/polars/tree/emscripten)) - I can build a wheel for Pyodide:

![371104753-f79226d6-c58b-47d7-af16-27f00b380488](https://github.com/user-attachments/assets/34656515-f1ed-434d-94cf-ba982a60e221)

The path to making this work properly is still a long one, but looks as follows:

1) Upstream LLVM patch to fix multiple `.init_array` symbols in Wasm objects.
2) Wait for a version of `rustc` to be released with the LLVM fixes included.
3) Update the inventory package to add `.init_array` symbols under WebAssembly.
4) Upstream patches to Polars to support the `wasm32-unknown-emscripten` target.

**Comment by georgestagg** [comment]
If you’d like to play with what I currently have up and running I’ve made a Pyodide wheel available to the JupyterLite server running at https://jupyter.r-wasm.org/lab/index.html?path=polars.ipynb

**Comment by agriyakhetarpal** [comment]
Hi @georgestagg, thanks for updating the rest of the items through your recent edits; I wonder if there are any other functional blockers for adding the recipe here in-tree for Pyodide? We're planning to get a 0.27 release out quite soon, and if everything is functional to a reasonable level for users, then I see no reason why we can't include it. :)

In particular, I'd like to know if the Rust nightly version in Pyodide you previously mentioned in https://github.com/pola-rs/polars/pull/20383 is still an issue, since we were trying to update it again in #5249.

If the Rust toolchain situation isn't conducive, you could also add a "stub" recipe and just paste the link to your wheel from the GitHub release URL – we've done the same thing for PyArrow to save up on CI time: please see https://github.com/joemarshall/pyarrow-pyodide/releases/tag/0.26.2 and https://github.com/pyodide/pyodide-numpy-2.0-rebuilds/releases/tag/v1.0.0 for examples. This will simply download the built wheel and copy it into the distribution folder without any compilation required (I noticed from https://github.com/georgestagg/polars/actions/runs/11274401446/job/31357836582 that it currently takes more than an hour to compile the wheel!).

**Comment by ritchie46** [comment]
Hey @agriyakhetarpal. Thanks to the help of @georgestagg we were able to build an emscripten wheel for Polars. It is now available under our Github releases. The latest available release is: 

https://github.com/pola-rs/polars/releases/tag/py-1.18.0

We release often once every 1/2 weeks.

**Comment by georgestagg** [comment]
> I wonder if there are any other functional blockers for adding the recipe here in-tree for Pyodide?

I think things are pretty much in place to go ahead and add Polars to Pyodide. We had to disable some Polars features to compile for Emscripten, due to some problematic Rust dependencies, but I expect we'll be able to re-enable most of them over time as more support Wasm.

> In particular, I'd like to know if the Rust nightly version in Pyodide you previously mentioned in https://github.com/pola-rs/polars/pull/20383 is still an issue, since we were trying to update it again in https://github.com/pyodide/pyodide/pull/5249.

To compile Polars for the `wasm32-unknown-emscripten` target, Rust `nightly-2024-12-19` or later is required. It looks like that PR only bumps you to `nightly-2024-12-02`, which would not be new enough.

> If the Rust toolchain situation isn't conducive, you could also add a "stub" recipe and just paste the link to your wheel from the GitHub release URL – we've done the same thing for PyArrow to save up on CI time [...] I noticed that it currently takes more than an hour to compile the wheel!

Interestingly it's the optimisation step that takes such a long time. A debug build is much quicker, though leads to an unusably large wheel.

I think with the toolchain requirement, and the long compile times, a stub recipe is the way to go at least for now. As Richie mentioned above, the Polars project now builds Emscripten wheels on release and can be found on their GitHub Releases page. I would point to this wheel using a stub recipe.

I'm going to be on leave for the next week or so. If someone else would like to take on adding the stub recipe to Pyodide during that time I'm happy for them to do so. Otherwise, I'll take another look once I'm back online.

**Comment by agriyakhetarpal** [comment]
Thanks both for the information and the additional context around the Emscripten builds. I'll open a PR for adding the recipe while keeping in mind the Rust nightly version requirement as a TODO item. Thanks for your tremendous work!
