### ISSUE TITLE
Major Difference on execution time between Firefox and Chrome

### ISSUE THREAD

**Issue by inesani** [pyodide/pyodide#491]
Hello,

I have downloaded a prebuild version of pyodide from here: https://github.com/iodide-project/pyodide/releases/ in order to develop a small app with Python that needs to run in the browser.

For this, i am loading three libraries, numpy, pandas and scikit learn with the loadPackage function. Basically I have modified the test.html file you provide on the pre-built version into something like this.

```html
<html> 
<head>
  <meta charset="utf-8" />
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <script src="../pyodide.js"></script>
  <script type="module" src="./launch.js"></script>
  <script>
    async function init() {
      const t0 = Date.now();
      console.info("Init");
      await languagePluginLoader;
      const t1 = Date.now();
      console.info("Before load packages " + (t1 - t0));
      await pyodide.loadPackage(['numpy', 'pandas', 'scikit-learn']);
      const t2 = Date.now();
      console.info("Loaded: " + (t1 - t0) + ", " + (t2 - t1));
      for (const i of [
        "numpy",
        "pandas",
        "sklearn.preprocessing",
        "sklearn.decomposition",
        "sklearn.cluster",
        "sklearn.metrics",
        "scipy.spatial.distance",
      ]) {
        console.info(`Importing ${i}`);
        await pyodide.runPython(`import ${i}`);
      }
      const t3 = Date.now();
      console.info("Imported: " + (t1 - t0) + ", " + (t2 - t1) + ", " + (t3 - t2));
      //Do Stuff: launch();
    }
    init();
  </script>
</head>

<body>
  <div style="margin: 40px" id="root"></div>
</body>

</html>
```
I am testing this locally with a basic Python web server.

I have noticed a very different behavior when executing this in Firefox and in Chrome when it comes to loading and importing python libraries.

For example, the above code in FIREFOX takes 1.88s to load the libraries and 24.45s to do the imports. Meanwhile, in CHROME it takes 30s to load them and 5.4s to import them. Anyone has a clue on why the execution patterns are so different? Is this happening to someone else?

Another thing that has surprised me is that after refreshing the browser tab a few times I get an  `uncaught exception: out of memory` in any of the two browsers even though I am not loading much data or many libraries.

Any help with this issues will be gladly appreciated as I am looking forward to continue working with Pyodide :)

**Comment by mdboom** [comment]
Yes, unfortunately this is a known issue (see https://github.com/iodide-project/pyodide/issues/386).

Chrome requires us to load any .wasm files larger than 4k asynchronously.  Unfortunately, Python is designed to load extension modules (`.so`) files synchronously through `dlopen` (which is a synchronous POSIX API).  Therefore, on Chrome, when you load the Scipy package, for example, it loads all of the extension modules *immediately* so that they can be loaded Python synchronously later when they actually get imported.  Since Firefox doesn't have this restriction, we only load the modules that the code actually uses, which is generally *much* less than "all of them".  In your code example above, it's even more extreme, since all it does is download the packages and not do any actual importing on Firefox, whereas on Chrome it is downloading the packages and then importing all of the extension modules within them.

There are some ways forward, all of which are experimental and somewhat blocked on upstream changes to emscripten:

1) Make it possible for Python to do synchronous things that are really asynchronous under the hood (made possible by the new asyncify LLVM pass in emscripten)
2) Reduce the size of the extension modules in Scipy by sharing a common copy of BLAS/LAPACK (the basis for this is mostly finished upstream in emscripten, but Pyodide needs to be updated to use it)

**Comment by guceda** [comment]
Thanks @mdboom for your help.

**Comment by rth** [comment]
Scipy size has been reduced a lot last year, and Chrome meanwhile has become significantly faster for WebAssembly so I think we can close this issue.

> Another thing that has surprised me is that after refreshing the browser tab a few times I get an uncaught exception: out of memory in any of the two browsers even though I am not loading much data or many libraries.

Yes, it's still the case. Apparently some sub-optimal garbage collection by web browsers. The solution is to open a new tab.
