### ISSUE TITLE
`sys.stderr` has no attribute `writelines`

### ISSUE THREAD

**Issue by vytas7** [pyodide/pyodide#5053]
Not sure if this is a bug or feature request, depends how one views it :slightly_smiling_face: 

## 🐛 Bug

`sys.stderr` inside Pyodide REPL has no attribute `writelines`. As per Python docs, [`sys.stderr`](https://docs.python.org/3/library/sys.html#sys.stderr) is a file object with the interface defined in the [`io` module](https://docs.python.org/3/library/io.html#io.IOBase), which includes the `writelines()` method.

### To Reproduce

Open [Pyodide REPL](https://pyodide.org/en/stable/console.html) in the browser.
Evaluate the following code in the REPL:
```python
>>> import sys
>>> sys.stderr.write('Hello, World!\n')
Hello, World!
>>> sys.stderr.writelines(['Hello, ', 'World!\n'])
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: '_WriteStream' object has no attribute 'writelines'
```

### Expected behavior

Running the same in CPython 3.12 proper:
```python
>>> import sys
>>> sys.stderr.write('Hello, World!\n')
Hello, World!
14
>>> sys.stderr.writelines(['Hello, ', 'World!\n'])
Hello, World!
```

(NB there is another potentially problematic difference that the Pyodide flavour does not return the number of bytes written.)

### Environment

https://pyodide.org/en/stable/console.html on Mozilla Firefox 130.0 (64-bit):
```
Welcome to the Pyodide 0.26.2 terminal emulator 🐍
Python 3.12.1 (main, Jul 26 2024 14:03:47) on WebAssembly/Emscripten
```

### Additional context

`None`

**Comment by hoodmane** [comment]
Thanks for the report @vytas7. This is indeed a bit sloppy. Seems like we could model what we do on this:
https://github.com/python/cpython/blob/1fdfce9452706a8a12ccdacff6d02c9231dc48ce/Lib/idlelib/run.py#L442-L525

Of course another possible approach would be to redirect the streams at the file descriptor level. If we made `/dev/tty2` and used `os.dup2` to redirect stdin/stdout/stderr then it would also catch C/C++/Rust code that writes to stdout or stderr. This would have to be in addition to the current system because this is public API and devices can't be implemented in Python. But if we added the option to pass a path, then we could make `/dev/tty2` and pass that as the path for stdin/stdout/stderr.
