### ISSUE TITLE
Update Build Github actions example to use cibuildwheel

### ISSUE THREAD

**Issue by viblo** [pyodide/pyodide#5061]
## 📚 Documentation

Now that Pyodide can be built with cibuildwheel I think it would be nice to update the Github action example with either a mention/example of cibuildwheel in case you want to keep the full "manual" way, or replace the whole thing with a cibuildwheel example. The numpy example that is linked is already using cibuildwheel, which is a bit confusing since the example mention a different way to build.

This is the place in docs: https://pyodide.org/en/stable/development/building-and-testing-packages.html#build-github-actions-example

**Comment by agriyakhetarpal** [comment]
Hi, @viblo! Thanks for proposing the improvement. Yes, think it would be better to include both ways of building it, instead of replacing it completely – since `cibuildwheel` removes the boilerplate, but the current method does allow for some customisation of the builds, after all.

Would you like to submit a PR?

**Comment by viblo** [comment]
I can absolutely do a pr, I will see if I can do it later today, otherwise I try something in the coming days.
