### ISSUE TITLE
pyodide-build should be a git submodule?

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#5122]
@ryanking13 what do you think? I think what we're doing with 
```
export PYODIDE_BUILD_COMMIT=...
export PYODIDE_BUILD_REPO=...
```
is just a poor man's git submodule.

**Comment by ryanking13** [comment]
Indeed. Sounds good to me.

**Comment by hoodmane** [comment]
Then we could get rid of `check_and_install_pyodide_build.py` and replace it with with `pip install -e ./pyodide-build`.

**Comment by danainacore** [comment]
[](url)

**Comment by agriyakhetarpal** [comment]
That sounds like a good idea! Note: the PYODIDE_BUILD_COMMIT currently points to a release commit. If we check out the latest commit in the submodule, we should ensure that `pyodide-build` never fails on `main`. Otherwise, we should ensure that the submodule is checked out to the latest release branch and periodically update it.
