### ISSUE TITLE
C++ exceptions not working as expected

### ISSUE THREAD

**Issue by johnwason** [pyodide/pyodide#545]
I am working on porting a project to run in Pyodide. My progress can be found here: https://github.com/johnwason/robotraconteur_pyodide . Because this project depends on Boost, CMake, and SWIG it can't be easily packaged using setuptools. Instead an external CMake build is used.

While testing, I discovered that C++ exceptions were not being caught. It appears that if a function throws an exception, it is not propagated to the calling function's catch handler. I was able to reproduce the problem in a toy problem: https://gist.github.com/johnwason/422b0bd9787088db3d12b422a6a835ff . Run `build.sh`, then in the `console.html` of pyodide run

    import pyodide_exception_test_module
    pyodide_exception_test_module.test_exceptions(0)

Looking at the browser debug console output, this seems to silently fail to handle the exception thrown in `test_exception2()`. It should catch the exception and propagate it to python through `PyErr_SetString`. If the exception is thrown within `test_exception()`, it works as expected.

Why am I seeing this behavior, and is there a way to correct it?

I had to use this patch to load the modules  https://github.com/iodide-project/pyodide/issues/507, not sure if that is affecting anything.

**Comment by PythonLinks** [comment]
@johnwason, I know someone who has a closed source version of Make written in Python.  I do not know if that would help you or not.  Maybe just email me at lozinski@PythonLinks.info.

I am not a Data Scientist, but I think that a lot of data science could benefit from something like that.   A single computer version of AirFlow.  Much better than manually trying to figure out in which order to run things.

**Comment by johnwason** [comment]
I got exceptions to work by statically linking the module into the main module and using `PyImport_AppendInittab` to load it in to python. There still appears to be an issue with C++ exceptions in side modules, but for my purposes static linking is fine.

**Comment by mgreminger** [comment]
I can confirm that this issue is occurring with the nlopt package as well. Exceptions that are thrown in the C++ extension cannot be caught in Python with a try-except block even when when using `except:`, which should catch all exceptions. The exceptions show up in the browser console as `uncaught exception: 11670528` where the number varies. The original exception name and message are lost. These are exceptions that can be caught successfully when nlopt is used outside of the Pyodide environment. Emscripten [by default](https://emscripten.org/docs/optimizing/Optimizing-Code.html#c-exceptions) does not catch C++ exceptions with optimization of -O1 and above. However, I did try comping all of Pyodide and all of the extensions with the `-s DISABLE_EXCEPTION_CATCHING=0` option to enable exception catching from C++ code. This made the issue worse since all of the exceptions were silently ignored. The current behavior is better since the exceptions do raise up the the javascript level at least. 

I don't think there is a good solution currently. I mainly just wanted to confirm this issue and to provide information in case users of the nlopt Pyodide package run into this issue. If if setting `-s DISABLE_EXCEPTION_CATCHING=0` worked, it's not likely a performance and size hit we would want to take for a all of the packages to fix a few isolated issues with C++ extensions. The [emscripten doc](https://emscripten.org/docs/optimizing/Optimizing-Code.html#c-exceptions) does state the following: 

> eventually, wasm should gain native support for exceptions, and not have this issue

so hopefully this issue will eventually be resolved as wasm gains more features.

**Comment by johnwason** [comment]
This appears to be a problem with emscripten. The issue has been confirmed as part of the issue I opened there: https://github.com/iodide-project/pyodide/issues/545

**Comment by johnwason** [comment]
This related commit says something about enabling exceptions for support libraries too:

https://github.com/belraquib/emscripten/commit/28f1cb3a2698bff680a38641377f59b21c9ccd4b

**Comment by johnwason** [comment]
This seems to be working with emscripten version 3.1.13 and `-fexceptions`

**Comment by hoodmane** [comment]
For the record, it was fixed by adding this line:
https://github.com/pyodide/pyodide/blob/f5925944a21dad413e0a3376fda82896b11e35b2/Makefile.envs#L145

**Comment by johnwason** [comment]
After looking at the documentation a bit, I realized that I wasn't enabling WASM exceptions they way I had expected. I have them working but it requires setting `-fwasm-exceptions -lexceptions.js` in `MAIN_MODULE_LDFLAGS`, otherwise the symbol `__cpp_exception` is missing.

**Comment by nayankr-jain** [comment]
pyodide.asm.js:9 Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.

pyodide.asm.js:9 CppException geos::util::TopologyException: TopologyException: found non-noded intersection between LINESTRING (-82.5 27.3508, -82.5 27.3508) and LINESTRING (-82.5 27.3508, -82.5 27.3508) at -82.499973999999995 27.350833000000002
    at convertCppException (https://cdn.jsdelivr.net/pyodide/v0.23.4/full/pyodide.asm.js:9:102351)
    at API.fatal_error (https://cdn.jsdelivr.net/pyodide/v0.23.4/full/pyodide.asm.js:9:102761)
    at Module.callPyObjectKwargs (https://cdn.jsdelivr.net/pyodide/v0.23.4/full/pyodide.asm.js:9:75641)
    at Module.callPyObject (https://cdn.jsdelivr.net/pyodide/v0.23.4/full/pyodide.asm.js:9:75942)
    at wrapper (https://cdn.jsdelivr.net/pyodide/v0.23.4/full/pyodide.asm.js:9:57697)


I am using the lastest version of pyodide and trying to catch this exception using try except block but I am not able to catch this exception. 

Reference:
I am using python shapely package in pyodide on frontend (Reactjs).
