### ISSUE TITLE
Run pyodide in non browser WA runtime

### ISSUE THREAD

**Issue by alzpublic** [pyodide/pyodide#558]
Is it possible to run pyodide in runtimes like WAVM or Wasmer? I've tried to ti start `pyodide.asm.wasm` doesn't work. Is there a special version of pyodide?

**Comment by rth** [comment]
> Is it possible to run pyodide in runtimes like WAVM or Wasmer?

Not at the moment I think. Several thing would be necessary for this, as far as I understand,
 - that emscripten moves toward a better support of those cf https://github.com/emscripten-core/emscripten/issues/9479#issuecomment-534255166 and later discussion
 - that pyodide updates to use the latest emscripten version (https://github.com/iodide-project/pyodide/pull/531) which would require some work.

**Comment by filips123** [comment]
Wasmer currently uses [fork for Pyodide](https://github.com/wapm-packages/pyodide) with some modifications. You could maybe contact Wasmer developers for more details how to support it in official Pyodide version.

**Comment by maxmcd** [comment]
I know it hasn't been very long, but any update on this? Maybe more specifically: would pyodide eventually switch to using wasi?

**Comment by owenthereal** [comment]
👋 Any update on this? I'm looking forward to seeing pyodide to run on a wasi capable runtime like wasmtime or wasmer. Is there anything that I could help?

**Comment by hoodmane** [comment]
Quote from @owenthereal in gitter

> Specifically, I think we need to feed `-s STANDALONE_WASM` into `emcc`: https://github.com/emscripten-core/emscripten/wiki/WebAssembly-Standalone. But I'm not familiar enough with the build process of `pyodide` to get it to work

Pyodide uses very large amounts of `EM_JS`, which also assumes we can call out to arbitrary code in a Javascript runtime. All of the `EM_JS` code will also need to be addressed. I think I would need to understand what the use cases look like a bit better to give any advice about how to proceed.

**Comment by owenthereal** [comment]
>  I think I would need to understand what the use cases look like a bit better to give any advice about how to proceed.

I would like to run pyodide in wasmtime in a serverless environment. Basically, an HTTP request triggers the run of a python script which is run in the pyodide standalone wasm in wasmtime. The goal is to run python scripts in a safe & isolated environment. Let me know if you have questions about the use case. I'm happy to elaborate more (I also pinged you on Gitter if that's a better place for Q/A back & forth).

**Comment by hoodmane** [comment]
I guess the question is whether it is a problem for you to run all the `EM_JS` Javascript code in node. You could change it so that the `js` module only exposes `fetch`, `Object`, and `setTimeout`, and so that `pyodide_js` only exposes `loadPackagesFromImports`. Hard to know whether this would be secure or not. This doesn't give the user any direct ability to execute arbitrary Javascript, but maybe they could break out somehow? Related: #959.

**Comment by hoodmane** [comment]
Perhaps you can even shim `setTimeout` and `fetch` with WASI and just make `Object` into a empty class (this last will break a few functions). Then you can make a `js` module that doesn't actually import from Javascript.

So the question is whether the user can break out from the `EM_JS` fixed blobs of Javascript into executing arbitrary Javascript. It sounds difficult but plausible for a sufficiently motivated user.

**Comment by bachp** [comment]
I am also interested in this.

My use case is to run some user provided python script in a secure way. The idea is to make use of the sanbox provided by the WASM runtime and executing the python code inside using pyodide.

The assumption is that a WASI compatible runtime (e.g. wasmer or wasmtime) and the [Capability-based security](https://github.com/WebAssembly/WASI#capability-based-security) it provides, would ensure that the python script can only interact with the resources explicitly given to the it via the runtime.

**Comment by hoodmane** [comment]
I think WASI is generally out of scope for us. For now, `wasm32-wasi` is too different than `wasm32-emscripten`. A lot of our stuff strongly supposes the presence of a Javascript runtime, which is an assumption that is not true in WASI so our loader code won't work. Our FFI code is to connect Javascript <--> Python, so that makes no sense. WASI doesn't have dynamic linking so we can't load packages and our package loading code doesn't work.

It is worth noting that Python 3.11 should support WASI as a target out of the box. You can try out Python 3.11a6 I think it should not be hard to build it to target WASI (I could be wrong @tiran can probably tell you whatever you need to know).

Of course that would only get you the standard library, statically linking in things like numpy is another story.

**Comment by rth** [comment]
> I think WASI is generally out of scope for us.

I agree for the above-mentioned reason. Too much of our code base requires Javascript, and is tightly coupled with Emscripten (which also uses Javascript). So Python + Python packages on WASI should be a separate project. The only way to run server-side for Pyodide is to use Node.js.

Closing as "won't implement".

**Comment by MInner** [comment]
While researching this question I stumbled upon the following (outdated) repo: https://github.com/wapm-packages/pyodide
