### ISSUE TITLE
Question: How does the speed compare to plain old javascript for regular javascript type stuff?

### ISSUE THREAD

**Issue by Frick-David** [pyodide/pyodide#776]
I am trying to evaluate whether I want to incorporate this into my stack or not. I tried brython but it always seemed a little hacky to me. I saw this and am pretty excited about it. I am not sure I would use most of the libraries, just mainly the use of python instead of javascript for dynamic content. I was wondering how the speed of this library compares to regular javascript for pretty standard stuff.

I think a lot of my work revolves around adding event listeners to process data on the server (in flask) and then rendering content based on it.

Is python to web assembly faster than plain old javascript?

**Comment by Frick-David** [comment]
<!DOCTYPE html>
<html>
<head>
<script src="https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js"></script>
<script>
   // init environment
  languagePluginLoader
    // then run Python code
    .then(() => console.log(pyodide.runPython(`import sys; sys.version`)));
</script>
</head>
<body>
</body>
</html>

**Comment by Frick-David** [comment]
Here is a code example:
```
<!DOCTYPE html>
<html>
<head>
  <script src="https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js"></script>
  <script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
<script>

  languagePluginLoader
  .then(() => {
  pyodide.runPython(`
import sys
import datetime
sys.version`)
pyodide.runPython(`
def test():
	return 1 + 1
  `)
pyodide.runPython(`
import js

our_div = js.document.createElement('div')
our_div.style.backgroundColor = 'red'
our_div.style.width = '50px'
our_div.style.height = '50px'
js.document.body.appendChild(our_div)

my_tbl = js.document.createElement('table')


numbers = [1, 2, 3, 4]
for n in numbers:
	row = my_tbl.insertRow()
	cell = row.insertCell()
	cell.innerHTML = n;	

js.document.body.appendChild(my_tbl)

from js import Plotly

graph_div = js.document.getElementById('graph')
import random

randomlist = []

for i in range(0,500):
	n = random.randint(1,30)
	randomlist.append(n)

trace = {
    'x': randomlist,
    'type': 'histogram',
}
data = [trace]
Plotly.newPlot(graph_div, data)

import datetime
x = datetime.datetime.now().strftime("%x")
print(x) 

`)

})
</script>
</head>
<body>
<div id="my-div"></div>
<div id="graph"></div>

</body>
</html>
```

**Comment by subwaymatch** [comment]
In theory, it could be faster. 🙄

1. Depending on what you're trying to do, it _could_ be faster. As an example, using NumPy to run matrix computations would be far faster than for loops in JS.
2. Pyodide shares your main JS thread unless you use web workers. This means that your site completely freezes while Python code is running (in terms of UX, this is terrible). Web workers with Pyodide have reported issues that haven't been fixed yet (and probably won't be fixed since the project is not maintained anymore).
3. Pyodide is not stable enough for you to use it in any sort of real-world project 😥, and it probably ever won't be. It's sad to say that since Pyodide is my #1 open-source project.

These are my opinion based on some experimental stuff I've tried with Pyodide. 

- Run data analysis with Pandas (https://gold.is/)
- Use it to embed coding questions for a Python course (https://accy570.org/course/unit-04/number-types/integers)

**Comment by rth** [comment]
> and probably won't be fixed since the project is not maintained anymore

I beg to differ. It is maintained, just not too actively developed. Fixing some of the points you mentioned would require significant time investment, but it's should be doable. We are very welcome to contributions working in that direction.

> my work revolves around adding event listeners to process data on the server (in flask) and then rendering content based on it.

It's hard to tell short of benchmarking. We have [some benchmarks](https://github.com/iodide-project/pyodide/tree/master/benchmark) comparing native Python speed with that of running Python in pyodide,
![image](https://user-images.githubusercontent.com/630936/97547405-1159fe80-19ce-11eb-870b-eae6ae39acb7.png)

so generally it's 4-8 time slower for pure python, and 1-2 slower for Python code that used lots of c-extensions (e.g. numpy). There is some evidence, [Node js might be somewhat faster than native Python](https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/python.html) (on the benchmarks they considered) but how that translated to your specific use case is hard to tell without benchmarking.

**Comment by subwaymatch** [comment]
@rth Sorry about that 😐. I made a false assumption based on Iodide repo's "no longer development/maintain" message. I'm glad to hear that my favorite project is alive 🙏.

Question - is Pyodide still backed by Mozilla?

**Comment by rth** [comment]
No worries @subwaymatch  :) Great that you were experimenting on those projects. 

> Question - is Pyodide still backed by Mozilla?

No, that's no longer the case (cf https://github.com/iodide-project/pyodide/issues/766#issuecomment-701456373).

**Comment by subwaymatch** [comment]
@rth Thanks for the clarification and all your efforts with this project 👍.

**Comment by Frick-David** [comment]
Thank you both for your comments. Is there an actively maintainer web assembly version of python? Brython seems a little glitchy for me. This seems to run pretty well for me although I have not necessarily tested it out. I certainly could try and help the project out, although I am not sure how much I could help.
I am looking for a decent way to avoid javascript, and have continuity between python on the backend and python on the frontend.
Any suggestions.

also, could I get some pointers on how to benchmark my code in this library versus native javascript?

@rth thanks for your answer regarding speed.
I do not necessarily plan to replace my backend with this per your answer as it is slower than python on the backend. Fair enough. How does the speed compare to frontend javascript?

I ran this in jsfiddle to show:
```
<!DOCTYPE html>
<html>
<head>
  <script src="https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js"></script>
  <script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
<script>
languagePluginLoader
.then(() => {
pyodide.runPython(`
import js

my_tbl = js.document.createElement('table')


numbers = [1, 2, 3, 4]
for n in numbers:
    row = my_tbl.insertRow()
    cell = row.insertCell()
    cell.innerHTML = n;    

js.document.body.appendChild(my_tbl)

from js import Plotly

graph_div = js.document.getElementById('graph')
import random

randomlist = []

for i in range(0,500):
    n = random.randint(1,30)
    randomlist.append(n)

trace = {
    'x': randomlist,
    'type': 'histogram',
}
data = [trace]
Plotly.newPlot(graph_div, data)


import datetime
date1 = datetime.datetime(2020, 5, 18).strftime('%x')
date2 = datetime.datetime(2020, 5, 19).strftime('%x')
date3 = datetime.datetime(2020, 5, 20).strftime('%x')

graph2_div = js.document.getElementById('graph2')

trace1 = {
  'x': [date1, date2, date3],
  'y': [10, 15, 13],
  'type': 'scatter'
}
data = [trace1]

Plotly.newPlot(graph2_div, data);

`)

})
</script>
</head>
<body>
<div id="my-div"></div>
<div id="graph"></div>
<div id="graph2"></div>

</body>
</html>
```
My typical workflow would be to create pretty standard dynamic content on webpages.
Process data from pandas on the backend to javascript to put into dashboards, addEventListeners, etc.
Really just replace run of the mill JS stuff with Python stuff.
It seems pretty feasible using this nice library. Is it faster than plain old javascript for say rendering content?
I am going to look into how to time this as we speak.
If possible I will try and support this project as well.

**Comment by ehfd** [comment]
I got to comment the reason it is not too actively maintained is that the current state does have space to improve, but it still works perfectly for most usages regarding scopes that Pyodide is mainly used in. Any pure Python module can be seamlessly loaded from PyPi, and the user who wants to integrate C binding modules can add a yaml setting file including the PyPi source tarball link (typically without any patches unless it is a huge package like SciPy, Pandas, or Numpy, of which are maintained by the team).
And the real good point is that you can build your own WASM version of your Python code and separately host it as well as directly including your Python code in the HTML source.
Pyodide is a very big light for data scientists and people in academia to build a web application run client-side (instead of flooding the server just because of having to run the Python interpreter server-side) using the industry standard Python data science stack.

**Comment by Frick-David** [comment]
I saw that article a while ago while is how I ended up here. I am trying to evaluate the best tool for my work. I tried brython but was not a huge fan. I will look into transcrypt since it is ahead of time compiled!

**Comment by ehfd** [comment]
Note that you are never going to import the full NumPy, SciPy stacks, or any package with C bindings with Transcrypt. Anvil looks interesting for me if I was gonna make a commercial full-stack platform instead of a fully client-side web app for use in academia.

**Comment by hoodmane** [comment]
Closed as answered.
