### ISSUE TITLE
Add Appache Arrow

### ISSUE THREAD

**Issue by Alex-Monahan** [pyodide/pyodide#802]
Hi All!

I am very early in my research of Pyiodide, and it looks great! I work on a team that uses both Python and JS and we push our data to the browser in Apache Arrow format. It would be great for us to be able to run Python in the browser as well, and to be able to use Apache Arrow as the interchange format between JS and Python. I saw some mention of this as a potential roadmap item in a few blogs online, as well as in the Talk Python to Me podcast. Is this something that you are actively working on, or have any plans to investigate in the near future?

Thanks!
-Alex

**Comment by rth** [comment]
Investigating Apache Arrow would be worthwhile. I think @vadimkantorov did some experiments in https://github.com/iodide-project/pyodide/issues/400#issuecomment-486837306 (cf linked notebook). 

I'm not really familiar with Arrow, but I guess the first step would be to have a serialization/deserialization mechanism between Python/JS based on it even if it means somes copies, then see if those copies could be avoided?

What I'm not sure about if it could be made to work using only the JS arrow package or do we absolutely need to be build it for python as well? Building pyarrow from source seems [non trivial](https://github.com/conda-forge/arrow-cpp-feedstock/blob/master/recipe/meta.yaml#L55) due to a large number of dependencies, and I'm a bit concerned about the complexity that would add to pyodide.

**Comment by Alex-Monahan** [comment]
I think they may have simplified the dependencies somewhat: https://arrow.apache.org/blog/2020/07/29/cpp-build-simplification/
Also, I know that there is a C level library that has been simplified also: https://github.com/cwida/duckdb/pull/866

I have very limited experience with it though!

**Comment by thadk** [comment]
Progress is being made in https://github.com/pyodide/pyodide/issues/2933 with some promising candidates and limitations observed, maybe this can be closed?

**Comment by ryanking13** [comment]
Yes, I'll close this and let #2933 can be used for further discussion.
