### ISSUE TITLE
Redundancies / differences between pyodide.loadPackage and micropip.install?

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#870]
It seems to me that `pyodide.loadPackage` and `micropip.install` have significant redundancies in their functionality. Is there any difference in their purpose? Which one is better? Could they be merged? If not, it would be good to add a very explicit explanation of their differences to the docs.

**Comment by rth** [comment]
The current situation is that, 
- `pyodide.loadPackage` loads packages built by pyodide and is guaranteed to resolve dependencies correctly (because we have only a single version per package in the dependency graph, so is very easy)
- `micropip.install` will load pure Python wheels from PyPi or other URLs. It will resolve dependencies when loading from PyPi, assuming that information is correctly provided by the PyPi JSON API (which [is not always the case](https://dustingram.com/articles/2018/03/05/why-pypi-doesnt-know-dependencies/)) and that dependencies are pure python wheels themselves (which is also not always the case). If a package is built in pyodide, it will fallback to `pyodide.loadPackage` regress (https://github.com/iodide-project/pyodide/issues/725 is a known issue).

Personally I think that we should advertise `micropip.install`  more in the documentation and use it for everything, with `pyodide.loadPackage` being left as a more private function. Though the issue is then we are less able to guarantee that dependencies will be installed correctly. 

Another technical issue is that it would need loading micropip with `pyodide.loadPackage`. One solution could be to include `micropip` on core pyodide, though then we would need to make the build system more modular to be able to include micropip (and it's dependency distlib) into the core pyodide packages (which currently is not easily doable short of going back to Makefiles for those).

**Comment by hoodmane** [comment]
It would be great if you could either:
1. completely remove the distinction between `micropip.install` and `pyodide.loadPackage`, 
2. move `micropip.install` and `pyodide.loadPackage` onto the same object and give them names that somehow reflect their difference, or
3. merge them but add an argument to choose the behavior.

**Comment by hoodmane** [comment]
I guess part of what's confusing is there are approximately four ways to load a package:

1. by name from pyodide,
2. by name from pypi,
3. by url from a wheel,
4. by url from a javascript file 

both `loadPackage` and `install` do multiple of these. I think `loadPackage` can do 1 or 4 and `install` can do 1, 2, or 3? Perhaps we could expose four apis, each one that that specifically does a particular one of these four things and one "please be smart and choose for me" api? What's so confusing about the documentation is that we have two apis that each try to choose between several options.

Alternatively, if loading by name from pyodide is the safest option in that it has guaranteed dependency resolution, maybe name them by this? Then we could have two apis:
1. `loadPackageSafeDependencyResolution` which only loads objects by name from the pyodide repo (obviously choose a shorter name for this)
2. `loadPackage` which does option 4 if the requirement ends in .js, option 3 if the requirement ends in .whl, option 1 if the requirement is available in the pyodide repo, and attempts option 2 as a fallback?

**Comment by hoodmane** [comment]
Closed in favor of #1470.
