### ISSUE TITLE
Can't properly get a JS object back to Python

### ISSUE THREAD

**Issue by casatir** [pyodide/pyodide#892]
(This comes from [this comment](https://github.com/iodide-project/pyodide/pull/875#issuecomment-747369299))

When you get a Python object on the JS side (e.g. `runPython[Async]`'s result), it seems impossible to get it back into Python. As an illustration, compare the result of the two following code snippets:

```javascript
// returns "[object Object]"
pyodide.runPython("import js ; js.window.x = {1: 2} ; repr(js.window.x)")
// returns "{1: 2}"
pyodide.runPython("x = {1: 2} ; repr(x)")
```

Long story short,

``` javascript
pyodide.runPython("repr({1: 2})")
// is not equivalent to:
pyodide.pyimport("repr")(pyodide.runPython("{1: 2}"))
```

This is closely related to #780.

**Comment by hoodmane** [comment]
The specific problem here is that the definition of `_python2js_dict` is completely wrong: it performs a copy rather than proxying the dict. This is not the expected behavior at all: if `x` is a dict then `y=x` stores a reference to the same dict and `y[2] = 3` changes `x`. I think it's a major violation of expectations that `js.window.x = x` stores a copy of x, so that `js.window.x[2]=5` leaves `x` unchanged.

I think we need more tests for this kind of stuff.

https://github.com/iodide-project/pyodide/blob/641ce219b8d41d4f708f610106797c91abe1d734/src/type_conversion/python2js.c#L202

**Comment by hoodmane** [comment]
In `js2python` only immutable types get copied, whereas in `python2js` everything gets copied unless we can't figure out what it is. If we change `python2js` to only copy immutable types and proxy everything else then `js2python` and `python2js` will be inverses to each other like they ought to be and issues like this will be resolved.

It might be a good idea to expose an api to attempt to copy a jsproxy into a native python object and an api to copy a pyproxy into a native js object but these should require specific invocation.

**Comment by rth** [comment]
This now works as expected and produces identical results (thanks to @hoodmane's efforts),
```js
pyodide.runPython("repr({1: 2})")
pyodide.globals.get("repr")(pyodide.runPython("{1: 2}"))
```
