### ISSUE TITLE
Run tests in a WebKit based browser (or Safari) in CI

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#989]
It's would a bit difficult to run tests in Safari, but I think having tests with some other WebKit based browser available on Linux (e.g. Midori) would already be quite useful. 

ref: https://github.com/iodide-project/pyodide/issues/721

**Comment by hoodmane** [comment]
Do we have to support Safari? It seems like an outlier on caniuse, there's a whole pile of features that were implemented in Chromium and Firefox several years ago that Safari still doesn't support. Pyodide intrinsically relies on a bunch of quite recent features.

**Comment by hoodmane** [comment]
For instance, in order to get keyboard interrupts to work in any form we will need `SharedArrayBuffer`, but Safari doesn't support it:
https://caniuse.com/sharedarraybuffer

**Comment by hoodmane** [comment]
Another example is WebGL2:
https://caniuse.com/?search=webgl2
I think it's fairly typical for Safari to be 3 years behind Mozilla / Chrome in feature support.

**Comment by oeway** [comment]
Also see here: https://webassembly.org/roadmap/ too many red crosses for Safari ;)

**Comment by rth** [comment]
> Do we have to support Safari? 

Well we don't necessarily have to, but the thing is that there is a number of MacOS and iOS users that keep reporting issue when using pyodide https://github.com/iodide-project/pyodide/issues/533#issuecomment-736928032. So if we could make it work (even with some features disabled) and without too much efforts on our side, it would be worth considering.

I opened this issue mostly to experiment, and see what actually breaks when we run the test suite.

**Comment by joemarshall** [comment]
I want this too - for remote teaching, as we still have some students with Macs. 

I was going to build an alternative conftest.py that routed things through playwright instead of selenium. In theory shouldn't be too hard, and playwright means recent WebKit as well as Firefox and Chrome. I think selenium can only run WebKit easily on Mac and I don't have access to any during lockdown. I will have a play and see how hard it is maybe.

Incidentally, a lot of WebKit features got fixed on webkit 14, and Mac users surely should have recent Safari, so I think the basis for running in WebKit might well be there now, at least better than on that link above.

**Comment by rth** [comment]
> I was going to build an alternative conftest.py that routed things through playwright instead of selenium.

Interesting. Looks like playwright aims to also solve some of the test reliability issues with browser testing. Though for the random failures we saw in CI occasionally it's hard to tell if it's due to selenium or pyodide. Not sure how how good [playwright-python](https://github.com/microsoft/playwright-python) is, as it's fairly new.

**Comment by joemarshall** [comment]
Right, hacked something together now. 

The good: The core tests pass on webkit. I think webkit 14 has just about nailed the feature set required for using pyodide and other wasm stuff. It was released properly mid last year, so that means most apple things should be running it I think. 

The bad: Playwright devs can't get webkit working on debian in headless mode, it crashes for some reason. This means it has to be run through a virtual framebuffer thing. It also requires a bunch of things from debian multimedia and others which aren't in the standard debian packages. It was pretty trivial to make playwright run tests on firefox and chromium in the standard pyodide docker but then it wasn't happy running webkit for me and I didn't spend too much time fiddling with it. 

I did however boot up the playwright docker image with the various browser dependencies and run tests on there. What I've done so far with this is just modify conftest.py to run everything through playwright, so rather than the various selenium fixtures in there, there is a single playwright wrapper which implements all the calls the previous selenium wrappers used, and handles the various bits and pieces that the current tests need in order to work. Other than that, there are a couple of places in the package and core tests where webkit needs to be added to a list of browsers, but that is basically it. It's pretty straightforward. 

I've attached my conftest.py in case anyone is interested in it.

[conftest.zip](https://github.com/iodide-project/pyodide/files/5926343/conftest.zip)

**Comment by joemarshall** [comment]
Incidentally, playwright also hangs sometimes on tests or times out, which leads me to think that it is not just that selenium does bad things, but something about how tests call through to the local server.

**Comment by rth** [comment]
Thanks for all the exploratory work you did @joemarshall !

It might be easier to run actual Safari in a [MacOS instance on CircleCI](https://circleci.com/docs/2.0/executor-types/). Selenium should support it as far as I can tell.

**Comment by rth** [comment]
Thanks for the report @ivanistheone ! Would you mind opening separate issues about those (you can just copy paste the jupyterlite issues you opened and close them in jupyterlite mentioning they are moved there)? There is no good way of moving issues between repos unfortunately. As this issue is more about adding tests in CI in general rather than investigating specific failures. Thanks, and exciting work on Sympy live!

**Comment by ryanking13** [comment]
Closing as we now run the full test suite in Safari in MacOS (#2578, #3095). In the future, it would be nice if we can run these tests in Linux with WebKit through playwright.
